/**
 * Training Titles - Additional Genres (Comedy, Slice of Life, BL, GL, etc.)
 */

import type { MangaTitle } from './types';

export const ADDITIONAL_TITLES: MangaTitle[] = [
  // Comedy & Slice of Life
  { title: 'Gintama', alternativeTitles: [] },
  { title: 'Grand Blue Dreaming', alternativeTitles: ['Grand Blue'] },
  { title: 'Hinamatsuri', alternativeTitles: [] },
  { title: 'Asobi Asobase', alternativeTitles: [] },
  { title: 'Daily Lives of High School Boys', alternativeTitles: ['Danshi Koukousei no Nichijou'] },
  { title: 'Nichijou', alternativeTitles: ['My Ordinary Life'] },
  { title: 'Lucky Star', alternativeTitles: [] },
  { title: 'K-On!', alternativeTitles: [] },
  { title: 'Azumanga Daioh', alternativeTitles: [] },
  { title: 'Yotsuba&!', alternativeTitles: ['Yotsubato!'] },
  { title: 'Barakamon', alternativeTitles: [] },
  { title: 'Silver Spoon', alternativeTitles: ['Gin no Saji'] },
  { title: 'Laid-Back Camp', alternativeTitles: ['Yuru Camp'] },
  { title: 'Non Non Biyori', alternativeTitles: [] },
  { title: 'Flying Witch', alternativeTitles: [] },
  { title: 'Sweetness and Lightning', alternativeTitles: ['Amaama to Inazuma'] },
  { title: "Miss Kobayashi's Dragon Maid", alternativeTitles: [] },
  { title: 'Gabriel DropOut', alternativeTitles: [] },
  { title: 'The Way of the Househusband', alternativeTitles: ['Gokushufudou'] },
  { title: 'Sakamoto Desu ga?', alternativeTitles: ["Haven't You Heard? I'm Sakamoto"] },
  { title: 'Prison School', alternativeTitles: [] },
  { title: 'Golden Time', alternativeTitles: [] },
  { title: 'Toradora!', alternativeTitles: [] },
  { title: 'Gekkan Shoujo Nozaki-kun', alternativeTitles: ["Monthly Girls' Nozaki-kun"] },
  { title: 'Tsurezure Children', alternativeTitles: [] },
  { title: 'ReLIFE', alternativeTitles: [] },
  { title: 'Working!!', alternativeTitles: ['Wagnaria!!'] },
  { title: 'Blend S', alternativeTitles: [] },
  { title: 'New Game!', alternativeTitles: [] },
  { title: 'Pop Team Epic', alternativeTitles: [] },
  { title: 'Boku no Kokoro no Yabai Yatsu', alternativeTitles: ['The Dangers in My Heart'] },
  { title: 'Call of the Night', alternativeTitles: ['Yofukashi no Uta'] },
  { title: 'Skip and Loafer', alternativeTitles: [] },
  { title: "Don't Toy with Me, Miss Nagatoro", alternativeTitles: [] },
  { title: 'Uzaki-chan Wants to Hang Out!', alternativeTitles: [] },
  { title: 'Aharen-san wa Hakarenai', alternativeTitles: [] },
  { title: "Shikimori's Not Just a Cutie", alternativeTitles: [] },
  { title: 'Teasing Master Takagi-san', alternativeTitles: ['Karakai Jouzu no Takagi-san'] },
  // Food/Cooking
  { title: 'Yakitate!! Japan', alternativeTitles: [] },
  { title: 'Oishinbo', alternativeTitles: [] },
  { title: 'The Gourmet', alternativeTitles: ['Kodoku no Gourmet'] },
  { title: 'Bartender', alternativeTitles: [] },
  { title: 'Drops of God', alternativeTitles: ['Kami no Shizuku'] },
  { title: 'Wakako-zake', alternativeTitles: [] },
  // Music
  { title: 'Beck', alternativeTitles: ['Mongolian Chop Squad'] },
  { title: 'Given', alternativeTitles: [] },
  { title: 'Kids on the Slope', alternativeTitles: ['Sakamichi no Apollon'] },
  { title: 'Detroit Metal City', alternativeTitles: [] },
  { title: 'Anonymous Noise', alternativeTitles: ['Fukumenkei Noise'] },
  { title: 'Bocchi the Rock!', alternativeTitles: [] },
  { title: 'Blue Giant', alternativeTitles: [] },
  // BL (Boys Love)
  { title: 'Sasaki and Miyano', alternativeTitles: ['Sasaki to Miyano'] },
  { title: 'Ten Count', alternativeTitles: [] },
  { title: 'Hitorijime My Hero', alternativeTitles: [] },
  { title: 'Junjou Romantica', alternativeTitles: ['Pure Romance'] },
  { title: 'Sekaiichi Hatsukoi', alternativeTitles: ["World's Greatest First Love"] },
  { title: 'Love Stage!!', alternativeTitles: [] },
  { title: 'Doukyuusei', alternativeTitles: ['Classmates'] },
  { title: 'Blue Flag', alternativeTitles: [] },
  { title: 'Our Dreams at Dusk', alternativeTitles: ['Shimanami Tasogare'] },
  { title: "My Brother's Husband", alternativeTitles: [] },
  { title: 'I Hear the Sunspot', alternativeTitles: [] },
  // GL (Girls Love)
  { title: 'Citrus', alternativeTitles: [] },
  { title: 'Bloom Into You', alternativeTitles: ['Yagate Kimi ni Naru'] },
  { title: 'Kase-san Series', alternativeTitles: [] },
  { title: 'Girl Friends', alternativeTitles: [] },
  { title: 'Whispered Words', alternativeTitles: ['Sasameki Koto'] },
  { title: 'Aoi Hana', alternativeTitles: ['Sweet Blue Flowers'] },
  { title: 'Revolutionary Girl Utena', alternativeTitles: ['Shoujo Kakumei Utena'] },
  { title: 'Adachi and Shimamura', alternativeTitles: [] },
  { title: "I'm in Love with the Villainess", alternativeTitles: [] },
  { title: 'Yuri Is My Job!', alternativeTitles: [] },
  { title: 'Whispering You a Love Song', alternativeTitles: [] },
  // Military/War
  { title: 'Vinland Saga', alternativeTitles: [] },
  { title: 'Kingdom', alternativeTitles: [] },
  { title: 'Golden Kamuy', alternativeTitles: [] },
  { title: 'Drifters', alternativeTitles: [] },
  { title: 'Blade of the Immortal', alternativeTitles: [] },
  { title: 'Vagabond', alternativeTitles: [] },
  { title: 'Lone Wolf and Cub', alternativeTitles: [] },
  { title: 'Shigurui', alternativeTitles: [] },
  { title: 'Basilisk', alternativeTitles: [] },
  { title: 'Afro Samurai', alternativeTitles: [] },
  { title: 'Legend of the Galactic Heroes', alternativeTitles: ['Ginga Eiyuu Densetsu'] },
  { title: 'Gate: Thus the JSDF Fought There', alternativeTitles: [] },
  // Ecchi/Harem
  { title: 'Rosario + Vampire', alternativeTitles: [] },
  { title: 'Monster Musume', alternativeTitles: [] },
  { title: 'High School DxD', alternativeTitles: [] },
  { title: 'Trinity Seven', alternativeTitles: [] },
  { title: 'Date A Live', alternativeTitles: [] },
  { title: 'The Asterisk War', alternativeTitles: [] },
  { title: 'Chivalry of a Failed Knight', alternativeTitles: ['Rakudai Kishi no Cavalry'] },
  { title: 'The Irregular at Magic High School', alternativeTitles: ['Mahouka Koukou no Rettousei'] },
  { title: 'Classroom of the Elite', alternativeTitles: [] },
];
