/**
 * Training Titles - Extended Collection (Psychological, Horror, Drama, Supernatural)
 */

import type { MangaTitle } from './types';

export const EXTENDED_TITLES: MangaTitle[] = [
  // Psychological
  { title: 'Liar Game', alternativeTitles: [] },
  { title: 'Kakegurui', alternativeTitles: ['Compulsive Gambler'] },
  { title: 'Alice in Borderland', alternativeTitles: ['Imawa no Kuni no Alice'] },
  { title: 'Tomodachi Game', alternativeTitles: ['Friends Game'] },
  { title: 'Usogui', alternativeTitles: ['The Lie Eater'] },
  { title: 'One Outs', alternativeTitles: [] },
  { title: 'Kaiji', alternativeTitles: ['Gambling Apocalypse Kaiji'] },
  { title: 'Akagi', alternativeTitles: [] },
  { title: 'Real Account', alternativeTitles: [] },
  { title: 'Darwin\'s Game', alternativeTitles: [] },
  { title: 'Ikigami: The Ultimate Limit', alternativeTitles: [] },
  { title: 'Mirai Nikki', alternativeTitles: ['Future Diary'] },
  { title: 'Battle Royale', alternativeTitles: [] },
  { title: 'Doubt', alternativeTitles: [] },
  { title: 'Judge', alternativeTitles: [] },
  { title: 'Secret', alternativeTitles: [] },
  { title: 'Gantz', alternativeTitles: [] },
  { title: 'All You Need Is Kill', alternativeTitles: [] },
  { title: 'Kamisama no Iutoori', alternativeTitles: ['As The Gods Will'] },

  // Horror
  { title: 'Uzumaki', alternativeTitles: [] },
  { title: 'Tomie', alternativeTitles: [] },
  { title: 'Gyo', alternativeTitles: [] },
  { title: 'The Enigma of Amigara Fault', alternativeTitles: [] },
  { title: 'Hellstar Remina', alternativeTitles: [] },
  { title: 'Shiver', alternativeTitles: [] },
  { title: 'Dissolving Classroom', alternativeTitles: [] },
  { title: 'Fragments of Horror', alternativeTitles: [] },
  { title: 'Fuan no Tane', alternativeTitles: ['Seeds of Anxiety'] },
  { title: 'Mieruko-chan', alternativeTitles: ['The Girl That Can See It'] },
  { title: 'Ibitsu', alternativeTitles: [] },
  { title: 'Hideout', alternativeTitles: [] },
  { title: 'Manhole', alternativeTitles: [] },
  { title: 'Another', alternativeTitles: [] },
  { title: 'Corpse Party', alternativeTitles: [] },
  { title: 'Higurashi When They Cry', alternativeTitles: ['Higurashi no Naku Koro ni'] },
  { title: 'Umineko When They Cry', alternativeTitles: ['Umineko no Naku Koro ni'] },
  { title: 'The Drifting Classroom', alternativeTitles: ['Hyouryuu Kyoushitsu'] },
  { title: 'Dragon Head', alternativeTitles: [] },
  { title: 'I Am a Hero', alternativeTitles: [] },
  { title: 'Apocalypse no Toride', alternativeTitles: ['Fort of Apocalypse'] },
  { title: 'High School of the Dead', alternativeTitles: [] },
  { title: 'Ajin', alternativeTitles: ['Demi-Human'] },
  { title: 'Tokyo Ghoul:re', alternativeTitles: [] },
  { title: 'Pumpkin Night', alternativeTitles: [] },
  { title: 'Ichi the Killer', alternativeTitles: [] },
  { title: 'MPD Psycho', alternativeTitles: [] },
  { title: 'Deadman Wonderland', alternativeTitles: [] },
  { title: 'Parasyte', alternativeTitles: ['Kiseijuu'] },

  // Drama & Slice of Life
  { title: 'Oyasumi Punpun', alternativeTitles: ['Goodnight Punpun'] },
  { title: 'Sangatsu no Lion', alternativeTitles: ['March Comes in Like a Lion'] },
  { title: 'A Silent Voice', alternativeTitles: ['Koe no Katachi'] },
  { title: 'Your Lie in April', alternativeTitles: ['Shigatsu wa Kimi no Uso'] },
  { title: 'Orange', alternativeTitles: [] },
  { title: 'ReLife', alternativeTitles: [] },
  { title: 'Ao Haru Ride', alternativeTitles: ['Blue Spring Ride'] },
  { title: 'Honey and Clover', alternativeTitles: ['Hachimitsu to Clover'] },
  { title: 'Chihayafuru', alternativeTitles: [] },
  { title: 'Usagi Drop', alternativeTitles: ['Bunny Drop'] },
  { title: 'Space Brothers', alternativeTitles: ['Uchuu Kyoudai'] },
  { title: 'Welcome to the NHK', alternativeTitles: ['NHK ni Youkoso!'] },
  { title: 'Solanin', alternativeTitles: [] },
  { title: 'Blue Period', alternativeTitles: [] },
  { title: 'Look Back', alternativeTitles: [] },
  { title: 'Goodbye, Eri', alternativeTitles: [] },
  { title: 'The Horizon', alternativeTitles: [] },
  { title: 'Dead Dead Demon\'s Dededede Destruction', alternativeTitles: [] },
  { title: 'I Want to Eat Your Pancreas', alternativeTitles: ['Kimi no Suizou wo Tabetai'] },
  { title: 'Three Days of Happiness', alternativeTitles: ['Jumyou wo Kaitotte Moratta'] },
  { title: 'Aku no Hana', alternativeTitles: ['The Flowers of Evil'] },
  { title: 'Onani Master Kurosawa', alternativeTitles: ['Masturbation Master Kurosawa'] },
  { title: 'Watashitachi no Shiawase na Jikan', alternativeTitles: ['Our Happy Hours'] },
  { title: 'Sakamichi no Apollon', alternativeTitles: ['Kids on the Slope'] },

  // Supernatural & Action
  { title: 'Noragami', alternativeTitles: [] },
  { title: 'Blue Exorcist', alternativeTitles: ['Ao no Exorcist'] },
  { title: 'D.Gray-man', alternativeTitles: [] },
  { title: 'Bungo Stray Dogs', alternativeTitles: [] },
  { title: 'Kekkaishi', alternativeTitles: [] },
  { title: 'Nurarihyon no Mago', alternativeTitles: ['Nura: Rise of the Yokai Clan'] },
  { title: 'Muhyo & Roji\'s Bureau of Supernatural Investigation', alternativeTitles: [] },
  { title: 'Yu Yu Hakusho', alternativeTitles: ['Ghost Fighter'] },
  { title: 'Shaman King', alternativeTitles: [] },
  { title: 'Ushio and Tora', alternativeTitles: [] },
  { title: 'Mononoke', alternativeTitles: [] },
  { title: 'Natsume\'s Book of Friends', alternativeTitles: ['Natsume Yuujinchou'] },
  { title: 'xxxHOLiC', alternativeTitles: [] },
  { title: 'The Morose Mononokean', alternativeTitles: ['Fukigen na Mononokean'] },
  { title: 'Toilet-bound Hanako-kun', alternativeTitles: ['Jibaku Shounen Hanako-kun'] },
  { title: 'InuYasha', alternativeTitles: [] },
  { title: 'Ranma 1/2', alternativeTitles: [] },
  { title: 'Urusei Yatsura', alternativeTitles: [] },
  { title: 'Maison Ikkoku', alternativeTitles: [] },
  { title: 'Rin-ne', alternativeTitles: ['Kyoukai no Rinne'] },

  // Seinen Action & Thriller
  { title: 'Berserk of Gluttony', alternativeTitles: ['Boushoku no Berserk'] },
  { title: 'Tsugumomo', alternativeTitles: [] },
  { title: 'Gleipnir', alternativeTitles: [] },
  { title: 'Fire Punch', alternativeTitles: [] },
  { title: 'Jagaaaaaan', alternativeTitles: [] },
  { title: 'Out', alternativeTitles: [] },
  { title: 'Crows', alternativeTitles: [] },
  { title: 'Worst', alternativeTitles: [] },
  { title: 'Rokudenashi Blues', alternativeTitles: [] },
  { title: 'Beelzebub', alternativeTitles: [] },
  { title: 'GTO', alternativeTitles: ['Great Teacher Onizuka'] },
  { title: 'Shonan Junai Gumi', alternativeTitles: [] },
  { title: 'Kyou kara Ore wa!!', alternativeTitles: [] },
  { title: 'Rainbow', alternativeTitles: ['Rainbow: Nisha Rokubou no Shichinin'] },
  { title: 'Sanctuary', alternativeTitles: [] },
  { title: 'Heat', alternativeTitles: [] },
  { title: 'Kiseijuu', alternativeTitles: ['Parasyte'] },
  { title: 'Terra Formars', alternativeTitles: [] },
  { title: 'Biomega', alternativeTitles: [] },
  { title: 'Knights of Sidonia', alternativeTitles: ['Sidonia no Kishi'] },
  { title: 'Blame!', alternativeTitles: [] },
  { title: 'ABARA', alternativeTitles: [] },
  { title: 'NOiSE', alternativeTitles: [] },
  { title: 'Aposimz', alternativeTitles: [] },

  // Romance & Comedy
  { title: 'Kaguya-sama: Love Is War', alternativeTitles: ['Kaguya-sama wa Kokurasetai'] },
  { title: 'The Quintessential Quintuplets', alternativeTitles: ['Go-Toubun no Hanayome'] },
  { title: 'Rent-A-Girlfriend', alternativeTitles: ['Kanojo, Okarishimasu'] },
  { title: 'Domestic Girlfriend', alternativeTitles: ['Domestic na Kanojo'] },
  { title: 'We Never Learn', alternativeTitles: ['Bokutachi wa Benkyou ga Dekinai'] },
  { title: 'Nisekoi', alternativeTitles: ['False Love'] },
  { title: 'Love Hina', alternativeTitles: [] },
  { title: 'Masamune-kun\'s Revenge', alternativeTitles: [] },
  { title: 'Yamada-kun and the Seven Witches', alternativeTitles: [] },
  { title: 'My Dress-Up Darling', alternativeTitles: ['Sono Bisque Doll wa Koi wo Suru'] },
  { title: 'Horimiya', alternativeTitles: [] },
  { title: 'Wotakoi', alternativeTitles: ['Love Is Hard for Otaku'] },
  { title: 'Komi Can\'t Communicate', alternativeTitles: ['Komi-san wa Comyushou desu'] },
  { title: 'Nagatoro-san', alternativeTitles: ['Don\'t Toy with Me, Miss Nagatoro'] },
  { title: 'Tonikaku Kawaii', alternativeTitles: ['Fly Me to the Moon'] },
  { title: 'Spy x Family', alternativeTitles: [] },
  { title: 'The Angel Next Door Spoils Me Rotten', alternativeTitles: [] },
  { title: 'My Senpai Is Annoying', alternativeTitles: [] },
  { title: 'Futari Ashita mo Sorenari ni', alternativeTitles: [] },
  { title: 'Yancha Gal no Anjou-san', alternativeTitles: [] },
  { title: 'Kubo Won\'t Let Me Be Invisible', alternativeTitles: [] },
  { title: 'Pseudo Harem', alternativeTitles: ['Giji Harem'] },
  { title: 'Insomniacs After School', alternativeTitles: ['Kimi wa Houkago Insomnia'] },

  // Historical & Period
  { title: 'Rurouni Kenshin', alternativeTitles: ['Samurai X'] },
  { title: 'Gintama', alternativeTitles: [] },
  { title: 'Samurai Champloo', alternativeTitles: [] },
  { title: 'Blade of the Immortal', alternativeTitles: ['Mugen no Juunin'] },
  { title: 'Dororo', alternativeTitles: [] },
  { title: 'Peacemaker Kurogane', alternativeTitles: [] },
  { title: 'Hakuouki', alternativeTitles: [] },
  { title: 'Angolmois', alternativeTitles: ['Record of Mongol Invasion'] },
  { title: 'The Elusive Samurai', alternativeTitles: ['Nige Jouzu no Wakagimi'] },
  { title: 'Issak', alternativeTitles: [] },
  { title: 'Innocent', alternativeTitles: [] },
  { title: 'Innocent Rouge', alternativeTitles: [] },
  { title: 'Otoyomegatari', alternativeTitles: ['A Bride\'s Story'] },
  { title: 'Emma', alternativeTitles: [] },
  { title: 'Isabella Bird in Wonderland', alternativeTitles: ['Fushigi no Kuni no Bird'] },

  // Mystery & Detective
  { title: 'Detective Conan', alternativeTitles: ['Case Closed'] },
  { title: 'Kindaichi Case Files', alternativeTitles: [] },
  { title: 'Monster', alternativeTitles: [] },
  { title: '20th Century Boys', alternativeTitles: [] },
  { title: 'Pluto', alternativeTitles: [] },
  { title: 'Billy Bat', alternativeTitles: [] },
  { title: 'Master Keaton', alternativeTitles: [] },
  { title: 'Death Note', alternativeTitles: [] },
  { title: 'Spiral: The Bonds of Reasoning', alternativeTitles: [] },
  { title: 'Moriarty the Patriot', alternativeTitles: ['Yuukoku no Moriarty'] },
  { title: 'Phantom Seer', alternativeTitles: [] },
  { title: 'Undead Unluck', alternativeTitles: [] },
  { title: 'Sakamoto Days', alternativeTitles: [] },
  { title: 'Mission: Yozakura Family', alternativeTitles: [] },
  { title: 'The Witch and the Beast', alternativeTitles: [] },
];
