/**
 * Training Titles - More Popular Manga
 */

import type { MangaTitle } from './types';

export const MORE_TITLES: MangaTitle[] = [
  // More Shonen Jump
  { title: 'Ayashimon', alternativeTitles: [] },
  { title: 'Nue\'s Exorcist', alternativeTitles: [] },
  { title: 'Dear Anemone', alternativeTitles: [] },
  { title: 'Super Smartphone', alternativeTitles: [] },
  { title: 'Gokurakugai', alternativeTitles: [] },
  { title: 'High School Family', alternativeTitles: [] },
  { title: 'Phantom Seer', alternativeTitles: [] },
  { title: 'PPPPPP', alternativeTitles: [] },
  { title: 'Aliens Area', alternativeTitles: [] },
  { title: 'Doron Dororon', alternativeTitles: [] },
  { title: 'Candy Flurry', alternativeTitles: [] },
  { title: 'Red Hood', alternativeTitles: [] },
  { title: 'Magu-chan: God of Destruction', alternativeTitles: [] },
  { title: 'Agravity Boys', alternativeTitles: [] },
  { title: 'Bone Collection', alternativeTitles: [] },
  { title: 'Guardian of the Witch', alternativeTitles: [] },
  { title: 'Time Paradox Ghostwriter', alternativeTitles: [] },
  { title: 'Hard-Boiled Cop and Dolphin', alternativeTitles: [] },
  { title: 'Build King', alternativeTitles: [] },
  { title: 'Cipher Academy', alternativeTitles: [] },
  { title: 'Jagaaaaaan', alternativeTitles: [] },
  { title: 'Green Worldz', alternativeTitles: [] },
  { title: 'Fire Punch', alternativeTitles: [] },
  { title: 'Tatsuki Fujimoto Short Stories', alternativeTitles: [] },
  // More Sports
  { title: 'Sumo Wrestling', alternativeTitles: [] },
  { title: 'Shoot! Goal to the Future', alternativeTitles: [] },
  { title: 'Sayonara Football', alternativeTitles: [] },
  { title: 'Aoashi', alternativeTitles: [] },
  { title: 'Farewell, My Dear Cramer', alternativeTitles: ['Sayonara Watashi no Cramer'] },
  { title: 'Knight of the Ice', alternativeTitles: ['Ginban Kishi'] },
  { title: 'Skating Rink Kaleidoscope', alternativeTitles: [] },
  { title: 'Medalist', alternativeTitles: [] },
  { title: 'Show-ha Shoten!', alternativeTitles: [] },
  { title: 'Act-Age', alternativeTitles: [] },
  { title: 'Glass Mask', alternativeTitles: [] },
  { title: 'Skip Beat!', alternativeTitles: [] },
  { title: 'Smile Down the Runway', alternativeTitles: ['Runway de Waratte'] },
  { title: 'Blue Period', alternativeTitles: [] },
  { title: 'Blank Canvas: My So-Called Artist\'s Journey', alternativeTitles: ['Kakukaku Shikajika'] },
  // More Romance
  { title: 'Insomniacs After School', alternativeTitles: ['Kimi wa Houkago Insomnia'] },
  { title: 'Sweat and Soap', alternativeTitles: ['Ase to Sekken'] },
  { title: 'Wotakoi: Love Is Hard for Otaku', alternativeTitles: [] },
  { title: 'The 100 Girlfriends Who Really Love You', alternativeTitles: [] },
  { title: 'Pseudo Harem', alternativeTitles: ['Giji Harem'] },
  { title: 'Dosanko Gal Is Mega Cute', alternativeTitles: [] },
  { title: 'Kubo Won\'t Let Me Be Invisible', alternativeTitles: [] },
  { title: 'The Ice Guy and His Cool Female Colleague', alternativeTitles: [] },
  { title: 'My Love Mix-Up!', alternativeTitles: ['Kieta Hatsukoi'] },
  { title: 'Kono Oto Tomare!', alternativeTitles: ['Sounds of Life'] },
  { title: 'Ao no Orchestra', alternativeTitles: ['Blue Orchestra'] },
  { title: 'Your Turn to Die', alternativeTitles: ['Kimi ga Shine'] },
  { title: 'Oshi no Ko', alternativeTitles: [] },
  { title: 'My Clueless First Friend', alternativeTitles: ['Jijou wo Shiranai Tenkousei ga Guigui Kuru'] },
  { title: 'Soredemo Ayumu wa Yosetekuru', alternativeTitles: ['When Will Ayumu Make His Move?'] },
  // More Horror/Thriller
  { title: 'Mieruko-chan', alternativeTitles: [] },
  { title: 'The Summer Hikaru Died', alternativeTitles: ['Hikaru ga Shinda Natsu'] },
  { title: 'Murciélago', alternativeTitles: [] },
  { title: 'Magical Girl Site', alternativeTitles: ['Mahou Shoujo Site'] },
  { title: 'Happy Sugar Life', alternativeTitles: [] },
  { title: 'Dead Mount Death Play', alternativeTitles: [] },
  { title: 'Call of the Night', alternativeTitles: [] },
  { title: 'Mission: Yozakura Family', alternativeTitles: [] },
  { title: 'Undead Girl Murder Farce', alternativeTitles: [] },
  { title: 'Spy Classroom', alternativeTitles: [] },
  { title: 'The Detective Is Already Dead', alternativeTitles: ['Tantei wa Mou, Shindeiru'] },
  { title: 'Moriarty the Patriot', alternativeTitles: ['Yuukoku no Moriarty'] },
  { title: 'Case Closed: Zero\'s Tea Time', alternativeTitles: [] },
  { title: 'Case Closed: The Culprit Hanzawa', alternativeTitles: [] },
  // More Seinen
  { title: 'Rooftop Sword Master', alternativeTitles: [] },
  { title: 'Sakamoto Days', alternativeTitles: [] },
  { title: 'Dandadan', alternativeTitles: [] },
  { title: 'Kaiju No. 8', alternativeTitles: [] },
  { title: 'Monster #8', alternativeTitles: [] },
  { title: '2.5 Dimensional Seduction', alternativeTitles: ['2.5-jigen no Ririsa'] },
  { title: 'Our Beloved Summer', alternativeTitles: [] },
  { title: 'A Bride\'s Story', alternativeTitles: ['Otoyomegatari'] },
  { title: 'Emma', alternativeTitles: [] },
  { title: 'Vinland Saga', alternativeTitles: [] },
  { title: 'Berserk', alternativeTitles: [] },
  { title: 'Vagabond', alternativeTitles: [] },
  { title: 'Real', alternativeTitles: [] },
  { title: 'Slam Dunk', alternativeTitles: [] },
  { title: 'Inoue Takehiko Works', alternativeTitles: [] },
  { title: 'Ayashimon', alternativeTitles: [] },
  { title: 'Monster', alternativeTitles: [] },
  { title: 'Naoki Urasawa Works', alternativeTitles: [] },
  // More Isekai/Fantasy
  { title: 'The Beginning After the End', alternativeTitles: ['TBATE'] },
  { title: 'Omniscient Reader\'s Viewpoint', alternativeTitles: [] },
  { title: 'Return to Player', alternativeTitles: [] },
  { title: 'The Constellation That Returned From Hell', alternativeTitles: [] },
  { title: 'Isekai Yakkyoku', alternativeTitles: ['Parallel World Pharmacy'] },
  { title: 'Uncle from Another World', alternativeTitles: ['Isekai Ojisan'] },
  { title: 'The Great Cleric', alternativeTitles: ['Seija Musou'] },
  { title: 'Campfire Cooking in Another World', alternativeTitles: [] },
  { title: 'I Shall Survive Using Potions!', alternativeTitles: ['Potion-danomi de Ikinobimasu!'] },
  { title: 'Didn\'t I Say to Make My Abilities Average?', alternativeTitles: [] },
  { title: 'In the Land of Leadale', alternativeTitles: [] },
  { title: 'Kuma Kuma Kuma Bear', alternativeTitles: [] },
  { title: 'Saving 80,000 Gold in Another World', alternativeTitles: ['Rougo ni Sonaete Isekai de 8-manmai no Kinka wo Tamemasu'] },
  { title: 'Management of a Novice Alchemist', alternativeTitles: ['Shinmai Renkinjutsushi no Tenpo Keiei'] },
  { title: 'She Profستs the Heroine', alternativeTitles: [] },
  { title: 'Reincarnated as the Piggy Duke', alternativeTitles: [] },
  { title: 'The Reincarnated Assassin is a Genius Swordsman', alternativeTitles: [] },
  // More Classic
  { title: 'Pluto', alternativeTitles: [] },
  { title: '20th Century Boys', alternativeTitles: [] },
  { title: 'Billy Bat', alternativeTitles: [] },
  { title: 'Master Keaton', alternativeTitles: [] },
  { title: 'Yawara!', alternativeTitles: [] },
  { title: 'Happy!', alternativeTitles: [] },
  { title: 'Pineapple Army', alternativeTitles: [] },
  { title: 'Naoki Urasawa\'s Manben', alternativeTitles: [] },
  { title: 'Mujirushi', alternativeTitles: [] },
  { title: 'Asadora!', alternativeTitles: [] },
  // More Shojo
  { title: 'A Condition Called Love', alternativeTitles: ['Hananoi-kun to Koi no Yamai'] },
  { title: 'Catch These Hands!', alternativeTitles: ['Watashi no Kobushi wo Uketomete!'] },
  { title: 'The One', alternativeTitles: [] },
  { title: 'Library Wars', alternativeTitles: ['Toshokan Sensou'] },
  { title: 'Otomen', alternativeTitles: [] },
  { title: 'Kare First Love', alternativeTitles: [] },
  { title: 'B.O.D.Y.', alternativeTitles: [] },
  { title: 'Hot Gimmick', alternativeTitles: [] },
  { title: 'Sensual Phrase', alternativeTitles: ['Kaikan Phrase'] },
  { title: 'Honey Hunt', alternativeTitles: [] },
  { title: 'Absolute Boyfriend', alternativeTitles: ['Zettai Kareshi'] },
  { title: 'Ai Yazawa Works', alternativeTitles: [] },
  { title: 'Paradise Kiss', alternativeTitles: [] },
  { title: 'Gokinjo Monogatari', alternativeTitles: ['Neighborhood Story'] },
  { title: 'Tenshi Nanka ja Nai', alternativeTitles: [] },
  { title: 'Kare Kano', alternativeTitles: ['His and Her Circumstances'] },
  { title: 'Yuu Watase Works', alternativeTitles: [] },
  { title: 'Imadoki!', alternativeTitles: ['Nowadays'] },
  { title: 'Alice 19th', alternativeTitles: [] },
  { title: 'Absolute Obedience', alternativeTitles: [] },
  // More Comedy
  { title: 'Genshiken', alternativeTitles: [] },
  { title: 'Otaku no Video', alternativeTitles: [] },
  { title: 'Welcome to the NHK', alternativeTitles: ['NHK ni Youkoso!'] },
  { title: 'I Can\'t Understand What My Husband Is Saying', alternativeTitles: [] },
  { title: 'Please Tell Me! Galko-chan', alternativeTitles: ['Oshiete! Galko-chan'] },
  { title: 'Handa-kun', alternativeTitles: [] },
  { title: 'Tanaka-kun is Always Listless', alternativeTitles: ['Tanaka-kun wa Itsumo Kedaruge'] },
  { title: 'Anne Happy', alternativeTitles: [] },
  { title: 'Is the Order a Rabbit?', alternativeTitles: ['Gochuumon wa Usagi Desu ka?'] },
  { title: 'Slow Start', alternativeTitles: [] },
  { title: 'Hidamari Sketch', alternativeTitles: [] },
  { title: 'GA: Geijutsuka Art Design Class', alternativeTitles: [] },
  { title: 'A-Channel', alternativeTitles: [] },
  { title: 'Acchi Kocchi', alternativeTitles: ['Place to Place'] },
  { title: 'Engaged to the Unidentified', alternativeTitles: ['Mikakunin de Shinkoukei'] },
  { title: 'Joshikousei no Mudazukai', alternativeTitles: ['Wasteful Days of High School Girls'] },
  { title: 'Mairimashita! Iruma-kun', alternativeTitles: ['Welcome to Demon School! Iruma-kun'] },
  { title: 'The Disastrous Life of Saiki K.', alternativeTitles: [] },
  { title: 'Haven\'t You Heard? I\'m Sakamoto', alternativeTitles: [] },
  { title: 'D-Frag!', alternativeTitles: [] },
  { title: 'Seitokai Yakuindomo', alternativeTitles: [] },
  // More Action
  { title: 'Veritas', alternativeTitles: [] },
  { title: 'The Breaker', alternativeTitles: [] },
  { title: 'Gamaran', alternativeTitles: [] },
  { title: 'Shura no Toki', alternativeTitles: [] },
  { title: 'Kenji', alternativeTitles: [] },
  { title: 'Worst', alternativeTitles: [] },
  { title: 'Crows', alternativeTitles: [] },
  { title: 'QP', alternativeTitles: [] },
  { title: 'Out', alternativeTitles: [] },
  { title: 'Rokudenashi Blues', alternativeTitles: [] },
  { title: 'Kyou kara Ore wa!!', alternativeTitles: [] },
  { title: 'Angel Densetsu', alternativeTitles: [] },
  { title: 'Rainbow: Nisha Rokubou no Shichinin', alternativeTitles: [] },
  { title: 'Sanctuary', alternativeTitles: [] },
  { title: 'Shamo', alternativeTitles: [] },
  { title: 'Tough', alternativeTitles: [] },
  { title: 'Karate Shoukoushi Kohinata Minoru', alternativeTitles: [] },
  { title: 'All-Rounder Meguru', alternativeTitles: [] },
  { title: 'Teppu', alternativeTitles: [] },
  { title: 'Rikudo', alternativeTitles: [] },
  // More Mystery
  { title: 'Q.E.D. iff', alternativeTitles: [] },
  { title: 'C.M.B.', alternativeTitles: [] },
  { title: 'Tantei Gakuen Q', alternativeTitles: ['Detective School Q'] },
  { title: 'Majin Tantei Nougami Neuro', alternativeTitles: [] },
  { title: 'File of Young Kindaichi', alternativeTitles: [] },
  { title: 'Conan', alternativeTitles: [] },
  { title: 'Death Note', alternativeTitles: [] },
  { title: 'Liar Game', alternativeTitles: [] },
  { title: 'Kaiji', alternativeTitles: [] },
  { title: 'Akagi', alternativeTitles: [] },
  { title: 'One Outs', alternativeTitles: [] },
  { title: 'Gambling Emperor Legend Zero', alternativeTitles: [] },
  { title: 'Usogui', alternativeTitles: [] },
  { title: 'Kakegurui', alternativeTitles: [] },
  { title: 'Tomodachi Game', alternativeTitles: [] },
  { title: 'Alice in Borderland', alternativeTitles: [] },
  { title: 'Darwin\'s Game', alternativeTitles: [] },
  { title: 'Real Account', alternativeTitles: [] },
  { title: 'Doubt', alternativeTitles: [] },
  { title: 'Judge', alternativeTitles: [] },
  // More Supernatural
  { title: 'Noragami', alternativeTitles: [] },
  { title: 'Blue Exorcist', alternativeTitles: [] },
  { title: 'D.Gray-man', alternativeTitles: [] },
  { title: 'Soul Eater', alternativeTitles: [] },
  { title: 'Ao no Exorcist', alternativeTitles: [] },
  { title: 'Nurarihyon no Mago', alternativeTitles: ['Nura: Rise of the Yokai Clan'] },
  { title: 'Kekkaishi', alternativeTitles: [] },
  { title: 'InuYasha', alternativeTitles: [] },
  { title: 'Yu Yu Hakusho', alternativeTitles: [] },
  { title: 'Shaman King', alternativeTitles: [] },
  { title: 'Mononoke', alternativeTitles: [] },
  { title: 'Mushishi', alternativeTitles: [] },
  { title: 'Natsume\'s Book of Friends', alternativeTitles: ['Natsume Yuujinchou'] },
  { title: 'xxxHolic', alternativeTitles: [] },
  { title: 'Tsubasa: Reservoir Chronicle', alternativeTitles: [] },
  { title: 'Tokyo Ravens', alternativeTitles: [] },
  { title: 'Twin Star Exorcists', alternativeTitles: ['Sousei no Onmyouji'] },
  { title: 'Spirit Circle', alternativeTitles: [] },
  { title: 'Lucifer and the Biscuit Hammer', alternativeTitles: ['Hoshi no Samidare'] },
  { title: 'Planet With', alternativeTitles: [] },
  // More Mecha
  { title: 'Mobile Suit Gundam Thunderbolt', alternativeTitles: [] },
  { title: 'Knights of Sidonia', alternativeTitles: [] },
  { title: 'Majestic Prince', alternativeTitles: ['Ginga Kikoutai Majestic Prince'] },
  { title: 'Break Blade', alternativeTitles: ['Broken Blade'] },
  { title: 'Flag', alternativeTitles: [] },
  { title: 'Regalia: The Three Sacred Stars', alternativeTitles: [] },
  { title: 'Comet Lucifer', alternativeTitles: [] },
  { title: 'Heavy Object', alternativeTitles: [] },
  { title: 'Schwarzesmarken', alternativeTitles: [] },
  { title: 'Muv-Luv Alternative', alternativeTitles: [] },
];
