/**
 * Training Titles - Niche but Popular Japanese Manga
 * Less mainstream titles that still have significant readership
 */

import type { MangaTitle } from './types';

export const NICHE_POPULAR_TITLES: MangaTitle[] = [
  // Gambling & Games
  { title: 'Saki', alternativeTitles: [] },
  { title: 'Hikaru no Go', alternativeTitles: [] },
  { title: 'Chihayafuru', alternativeTitles: [] },
  { title: 'March Comes in Like a Lion', alternativeTitles: ['3-gatsu no Lion'] },
  { title: 'Ryuuou no Oshigoto!', alternativeTitles: ['The Ryuo\'s Work is Never Done'] },
  { title: 'Gamble Fish', alternativeTitles: [] },
  { title: 'Shoukoku no Altair', alternativeTitles: ['Altair: A Record of Battles'] },

  // Medical & Science
  { title: 'Black Jack', alternativeTitles: [] },
  { title: 'Super Doctor K', alternativeTitles: [] },
  { title: 'Iryu: Team Medical Dragon', alternativeTitles: [] },
  { title: 'Hataraku Saibou', alternativeTitles: ['Cells at Work'] },
  { title: 'Cells at Work! Code Black', alternativeTitles: [] },
  { title: 'Dr. Stone', alternativeTitles: [] },
  { title: 'Heaven\'s Design Team', alternativeTitles: ['Tenchi Souzou Design-bu'] },
  { title: 'Moyashimon', alternativeTitles: [] },

  // Music & Arts (additional)
  { title: 'Shigatsu wa Kimi no Uso', alternativeTitles: ['Your Lie in April'] },
  { title: 'Nodame Cantabile', alternativeTitles: [] },
  { title: 'Piano no Mori', alternativeTitles: ['Forest of Piano'] },
  { title: 'Classicaloid', alternativeTitles: [] },
  { title: 'La Corda d\'Oro', alternativeTitles: ['Kin-iro no Corda'] },
  { title: 'Ongaku Shoujo', alternativeTitles: ['Music Girls'] },
  { title: 'Sound! Euphonium', alternativeTitles: ['Hibike! Euphonium'] },
  { title: 'Skip Beat!', alternativeTitles: [] },
  { title: 'Glass Mask', alternativeTitles: ['Glass no Kamen'] },
  { title: 'Bakuman', alternativeTitles: [] },
  { title: 'ReLIFE', alternativeTitles: [] },

  // Workplace & Adult Life
  { title: 'Aggretsuko', alternativeTitles: [] },
  { title: 'New Game!', alternativeTitles: [] },
  { title: 'Servant x Service', alternativeTitles: [] },
  { title: 'Densha Otoko', alternativeTitles: ['Train Man'] },
  { title: 'Hataraki Man', alternativeTitles: [] },
  { title: 'The Great Passage', alternativeTitles: ['Fune wo Amu'] },
  { title: 'Rikei ga Koi ni Ochita', alternativeTitles: ['Science Fell in Love'] },
  { title: 'Heaven?', alternativeTitles: [] },
  { title: 'Bambino!', alternativeTitles: [] },
  { title: 'Antique Bakery', alternativeTitles: [] },
  { title: 'Ristorante Paradiso', alternativeTitles: [] },
  { title: 'Thermae Romae', alternativeTitles: [] },

  // Modern Shonen & Action
  { title: 'Mashle', alternativeTitles: ['Mashle: Magic and Muscles'] },
  { title: 'Jujutsu Kaisen 0', alternativeTitles: [] },
  { title: 'Kaiju No. 8', alternativeTitles: [] },
  { title: 'Dandadan', alternativeTitles: [] },
  { title: 'Blue Box', alternativeTitles: ['Ao no Hako'] },
  { title: 'Akane-banashi', alternativeTitles: [] },
  { title: 'Elusive Samurai', alternativeTitles: ['Nige Jouzu no Wakagimi'] },
  { title: 'Witch Watch', alternativeTitles: [] },
  { title: 'Me & Roboco', alternativeTitles: ['Boku to Roboko'] },
  { title: 'Doron Dororon', alternativeTitles: [] },
  { title: 'Ayashimon', alternativeTitles: [] },
  { title: 'Cipher Academy', alternativeTitles: [] },
  { title: 'Neru', alternativeTitles: [] },
  { title: 'Aliens Area', alternativeTitles: [] },
  { title: 'High School Family', alternativeTitles: [] },
  { title: 'Earthchild', alternativeTitles: [] },
  { title: 'Super Smartphone', alternativeTitles: [] },
  { title: 'Ichinose-ke no Taizai', alternativeTitles: [] },

  // Supernatural Romance
  { title: 'Kamisama Kiss', alternativeTitles: ['Kamisama Hajimemashita'] },
  { title: 'Kakuriyo no Yadomeshi', alternativeTitles: [] },
  { title: 'Kyoukai no Rinne', alternativeTitles: ['Rin-ne'] },
  { title: 'Nurarihyon no Mago', alternativeTitles: [] },
  { title: 'Youkai Watch', alternativeTitles: [] },
  { title: 'Natsume Yuujinchou', alternativeTitles: ['Natsume\'s Book of Friends'] },
  { title: 'Fukigen na Mononokean', alternativeTitles: ['The Morose Mononokean'] },
  { title: 'Jibaku Shounen Hanako-kun', alternativeTitles: ['Toilet-bound Hanako-kun'] },
  { title: 'Youkai Apartment no Yuuga na Nichijou', alternativeTitles: [] },
  { title: 'Gegege no Kitarou', alternativeTitles: [] },

  // Seinen Slice of Life
  { title: 'Yotsuba&!', alternativeTitles: ['Yotsubato!'] },
  { title: 'Chi\'s Sweet Home', alternativeTitles: [] },
  { title: 'Yokohama Kaidashi Kikou', alternativeTitles: ['YKK'] },
  { title: 'Aria', alternativeTitles: [] },
  { title: 'Aqua', alternativeTitles: [] },
  { title: 'Sketchbook', alternativeTitles: [] },
  { title: 'Hidamari Sketch', alternativeTitles: [] },
  { title: 'Tamayura', alternativeTitles: [] },
  { title: 'Hanayamata', alternativeTitles: [] },
  { title: 'Mitsuboshi Colors', alternativeTitles: [] },
  { title: 'Ichigo Mashimaro', alternativeTitles: ['Strawberry Marshmallow'] },
  { title: 'Minami-ke', alternativeTitles: [] },
  { title: 'A-Channel', alternativeTitles: [] },
  { title: 'Kiniro Mosaic', alternativeTitles: ['KINMOZA!'] },
  { title: 'Gochiusa', alternativeTitles: ['Is the Order a Rabbit?'] },
  { title: 'Anne Happy', alternativeTitles: [] },
  { title: 'Slow Start', alternativeTitles: [] },
  { title: 'Comic Girls', alternativeTitles: [] },

  // Dark Fantasy
  { title: 'Claymore', alternativeTitles: [] },
  { title: 'Berserk: The Black Swordsman', alternativeTitles: [] },
  { title: 'Ubel Blatt', alternativeTitles: [] },
  { title: 'Goblin Slayer', alternativeTitles: [] },
  { title: 'Grimm\'s Fairy Tales', alternativeTitles: ['Ludwig Kakumei'] },
  { title: 'Pandora Hearts', alternativeTitles: [] },
  { title: 'The Case Study of Vanitas', alternativeTitles: ['Vanitas no Carte'] },
  { title: 'Black Butler', alternativeTitles: ['Kuroshitsuji'] },
  { title: 'D.Gray-man', alternativeTitles: [] },
  { title: 'Trinity Blood', alternativeTitles: [] },
  { title: 'Blood+', alternativeTitles: [] },
  { title: 'Blood-C', alternativeTitles: [] },
  { title: 'Hellsing', alternativeTitles: [] },
  { title: 'Drifters', alternativeTitles: [] },
  { title: 'The Dungeon of Black Company', alternativeTitles: [] },
  { title: 'Peter Grill and the Philosopher\'s Time', alternativeTitles: [] },
  { title: 'Redo of Healer', alternativeTitles: ['Kaifuku Jutsushi no Yarinaoshi'] },

  // Adventure & Fantasy
  { title: 'Radiant', alternativeTitles: [] },
  { title: 'Somali and the Forest Spirit', alternativeTitles: [] },
  { title: 'Children of the Whales', alternativeTitles: ['Kujira no Kora wa Sajou ni Utau'] },
  { title: 'Kemono Friends', alternativeTitles: [] },
  { title: 'Grimm\'s Notes', alternativeTitles: [] },
  { title: 'Wandering Witch', alternativeTitles: ['Majo no Tabitabi'] },
  { title: 'Kino\'s Journey', alternativeTitles: ['Kino no Tabi'] },
  { title: 'Spice and Wolf', alternativeTitles: ['Ookami to Koushinryou'] },

  // Mecha & Sci-Fi (additional)
  { title: 'Fafner in the Azure', alternativeTitles: ['Soukyuu no Fafner'] },
  { title: 'Sidonia no Kishi', alternativeTitles: ['Knights of Sidonia'] },
  { title: 'Blame!', alternativeTitles: [] },
  { title: 'Ghost in the Shell', alternativeTitles: ['Koukaku Kidoutai'] },
  { title: 'Appleseed', alternativeTitles: [] },
  { title: 'Eden: It\'s an Endless World!', alternativeTitles: [] },
  { title: 'Battle Angel Alita', alternativeTitles: ['Gunnm'] },
  { title: 'Akira', alternativeTitles: [] },
  { title: 'Grey', alternativeTitles: [] },
  { title: 'Macross', alternativeTitles: [] },
  { title: 'Patlabor', alternativeTitles: [] },

  // Card Games & Competitive
  { title: 'Yu-Gi-Oh!', alternativeTitles: [] },
  { title: 'Yu-Gi-Oh! GX', alternativeTitles: [] },
  { title: 'Yu-Gi-Oh! 5D\'s', alternativeTitles: [] },
  { title: 'Yu-Gi-Oh! ZEXAL', alternativeTitles: [] },
  { title: 'Yu-Gi-Oh! ARC-V', alternativeTitles: [] },
  { title: 'Yu-Gi-Oh! VRAINS', alternativeTitles: [] },
  { title: 'Cardfight!! Vanguard', alternativeTitles: [] },
  { title: 'Duel Masters', alternativeTitles: [] },
  { title: 'Medabots', alternativeTitles: ['Medarot'] },
  { title: 'Digimon Adventure V-Tamer 01', alternativeTitles: [] },
  { title: 'Digimon Next', alternativeTitles: [] },
  { title: 'Beyblade', alternativeTitles: [] },
  { title: 'B-Daman', alternativeTitles: [] },
  { title: 'Zatch Bell!', alternativeTitles: ['Konjiki no Gash!!'] },

  // Comedy (additional)
  { title: 'Cromartie High School', alternativeTitles: [] },
  { title: 'School Rumble', alternativeTitles: [] },
  { title: 'Pani Poni Dash!', alternativeTitles: [] },
  { title: 'Sayonara Zetsubou Sensei', alternativeTitles: [] },
  { title: 'Joshiraku', alternativeTitles: [] },
  { title: 'Aho Girl', alternativeTitles: [] },
  { title: 'D-Frag!', alternativeTitles: [] },
  { title: 'Seitokai Yakuindomo', alternativeTitles: [] },
  { title: 'Seitokai no Ichizon', alternativeTitles: [] },
  { title: 'Baka and Test', alternativeTitles: ['Baka to Test to Shoukanjuu'] },
  { title: 'Outbreak Company', alternativeTitles: [] },
  { title: 'No-Rin', alternativeTitles: ['Nourin'] },
  { title: 'Mayo Chiki!', alternativeTitles: [] },
  { title: 'MM!', alternativeTitles: [] },
  { title: 'Oreimo', alternativeTitles: ['My Little Sister Can\'t Be This Cute'] },
  { title: 'Eromanga Sensei', alternativeTitles: [] },
  { title: 'Ore no Imouto', alternativeTitles: [] },
  { title: 'The Pet Girl of Sakurasou', alternativeTitles: ['Sakurasou no Pet na Kanojo'] },

  // Sports (additional niche)
  { title: 'Days', alternativeTitles: [] },
  { title: 'Area no Kishi', alternativeTitles: ['The Knight in the Area'] },
  { title: 'Sayonara Football', alternativeTitles: ['Farewell, My Dear Cramer'] },
  { title: 'Ahiru no Sora', alternativeTitles: [] },
  { title: 'Real', alternativeTitles: [] },
  { title: 'I\'ll', alternativeTitles: [] },
  { title: 'Cross Game', alternativeTitles: [] },
  { title: 'Touch', alternativeTitles: [] },
  { title: 'Katsu!', alternativeTitles: [] },
  { title: 'Rough', alternativeTitles: [] },
  { title: 'H2', alternativeTitles: [] },
  { title: 'Adachi Mitsuru Works', alternativeTitles: [] },
  { title: 'Initial D', alternativeTitles: [] },
  { title: 'Wangan Midnight', alternativeTitles: [] },
  { title: 'MF Ghost', alternativeTitles: [] },
  { title: 'Over Drive', alternativeTitles: [] },
  { title: 'Noritake', alternativeTitles: [] },
  { title: 'Toppu GP', alternativeTitles: [] },
  { title: 'Capeta', alternativeTitles: [] },
];
