/**
 * Training Titles - Seinen Manga
 */

import type { MangaTitle } from './types';

export const SEINEN_TITLES: MangaTitle[] = [
  { title: 'Berserk', alternativeTitles: [] },
  { title: 'Vagabond', alternativeTitles: [] },
  { title: 'Vinland Saga', alternativeTitles: [] },
  { title: 'Monster', alternativeTitles: [] },
  { title: '20th Century Boys', alternativeTitles: [] },
  { title: 'Pluto', alternativeTitles: [] },
  { title: 'Billy Bat', alternativeTitles: [] },
  { title: 'Master Keaton', alternativeTitles: [] },
  { title: 'GANTZ', alternativeTitles: ['Gantz'] },
  { title: 'Inuyashiki', alternativeTitles: [] },
  { title: 'Gigant', alternativeTitles: [] },
  { title: 'Tokyo Ghoul', alternativeTitles: [] },
  { title: 'Tokyo Ghoul:re', alternativeTitles: [] },
  { title: 'Parasyte', alternativeTitles: ['Kiseijuu'] },
  { title: 'Golden Kamuy', alternativeTitles: [] },
  { title: 'Kingdom', alternativeTitles: [] },
  { title: 'Dorohedoro', alternativeTitles: [] },
  { title: 'Hellsing', alternativeTitles: [] },
  { title: 'Drifters', alternativeTitles: [] },
  { title: 'Blade of the Immortal', alternativeTitles: ['Mugen no Juunin'] },
  { title: 'Blame!', alternativeTitles: [] },
  { title: 'Knights of Sidonia', alternativeTitles: ['Sidonia no Kishi'] },
  { title: 'Biomega', alternativeTitles: [] },
  { title: 'Aposimz', alternativeTitles: [] },
  { title: 'Uzumaki', alternativeTitles: [] },
  { title: 'Tomie', alternativeTitles: [] },
  { title: 'Gyo', alternativeTitles: [] },
  { title: 'Remina', alternativeTitles: ['Hellstar Remina'] },
  { title: 'Sensor', alternativeTitles: [] },
  { title: 'No Longer Human', alternativeTitles: ['Ningen Shikkaku'] },
  { title: 'Ichi the Killer', alternativeTitles: [] },
  { title: 'Homunculus', alternativeTitles: [] },
  { title: 'Freesia', alternativeTitles: [] },
  { title: 'Ajin', alternativeTitles: ['Ajin: Demi-Human'] },
  { title: 'Sanctuary', alternativeTitles: [] },
  { title: 'Crying Freeman', alternativeTitles: [] },
  { title: 'Lady Snowblood', alternativeTitles: ['Shurayuki-hime'] },
  { title: 'Lone Wolf and Cub', alternativeTitles: ['Kozure Ookami'] },
  { title: 'Golgo 13', alternativeTitles: [] },
  { title: 'Liar Game', alternativeTitles: [] },
  { title: 'Kaiji', alternativeTitles: [] },
  { title: 'Akagi', alternativeTitles: [] },
  { title: 'Rainbow', alternativeTitles: ['Rainbow: Nisha Rokubou no Shichinin'] },
  { title: 'Real', alternativeTitles: [] },
  { title: 'Planetes', alternativeTitles: [] },
  { title: 'Historie', alternativeTitles: [] },
  { title: 'Space Brothers', alternativeTitles: ['Uchuu Kyoudai'] },
  { title: 'Blue Giant', alternativeTitles: [] },
  { title: 'Ao Ashi', alternativeTitles: [] },
  { title: 'Giant Killing', alternativeTitles: [] },
  { title: 'Holyland', alternativeTitles: [] },
  { title: 'Sun-Ken Rock', alternativeTitles: [] },
  { title: 'Kokou no Hito', alternativeTitles: ['The Climber'] },
  { title: 'I Am a Hero', alternativeTitles: [] },
  { title: 'Ikigami', alternativeTitles: ['Ikigami: The Ultimate Limit'] },
  { title: 'All You Need Is Kill', alternativeTitles: [] },
  { title: 'Gannibal', alternativeTitles: [] },
  { title: 'Blood on the Tracks', alternativeTitles: ['Chi no Wadachi'] },
  { title: 'Happiness', alternativeTitles: [] },
  { title: 'Aku no Hana', alternativeTitles: ['Flowers of Evil'] },
  { title: 'Goodnight Punpun', alternativeTitles: ['Oyasumi Punpun'] },
  { title: 'Solanin', alternativeTitles: [] },
  { title: 'A Girl on the Shore', alternativeTitles: ['Umibe no Onnanoko'] },
  { title: "Dead Dead Demon's Dededede Destruction", alternativeTitles: [] },
  { title: 'March Comes in Like a Lion', alternativeTitles: ['Sangatsu no Lion'] },
  { title: 'Honey and Clover', alternativeTitles: ['Hachimitsu to Clover'] },
  { title: 'Ping Pong', alternativeTitles: [] },
  { title: 'Sunny', alternativeTitles: [] },
  { title: 'Tekkon Kinkreet', alternativeTitles: ['Black and White'] },
  { title: 'Fire Punch', alternativeTitles: [] },
  { title: 'Goodbye, Eri', alternativeTitles: [] },
  { title: 'Look Back', alternativeTitles: [] },
  { title: 'Made in Abyss', alternativeTitles: [] },
  { title: "Girls' Last Tour", alternativeTitles: ['Shoujo Shuumatsu Ryokou'] },
  { title: 'Land of the Lustrous', alternativeTitles: ['Houseki no Kuni'] },
  { title: 'To Your Eternity', alternativeTitles: ['Fumetsu no Anata e'] },
  { title: 'A Silent Voice', alternativeTitles: ['Koe no Katachi'] },
  { title: 'Your Lie in April', alternativeTitles: ['Shigatsu wa Kimi no Uso'] },
  { title: 'I Want to Eat Your Pancreas', alternativeTitles: ['Kimi no Suizou wo Tabetai'] },
  { title: '5 Centimeters per Second', alternativeTitles: ['Byousoku 5 Centimeter'] },
  { title: 'Terra Formars', alternativeTitles: [] },
  { title: '7 Seeds', alternativeTitles: [] },
  { title: 'Coppelion', alternativeTitles: [] },
  { title: 'Kakegurui', alternativeTitles: [] },
  { title: 'Alice in Borderland', alternativeTitles: ['Imawa no Kuni no Alice'] },
  { title: 'Tomodachi Game', alternativeTitles: [] },
  { title: "Darwin's Game", alternativeTitles: [] },
  { title: 'Another', alternativeTitles: [] },
  { title: 'Higurashi When They Cry', alternativeTitles: ['Higurashi no Naku Koro ni'] },
  { title: 'MPD Psycho', alternativeTitles: [] },
  { title: 'Dragon Head', alternativeTitles: [] },
  { title: 'The Kindaichi Case Files', alternativeTitles: ['Kindaichi Shounen no Jikenbo'] },
  { title: 'Spiral: The Bonds of Reasoning', alternativeTitles: ['Spiral: Suiri no Kizuna'] },
  { title: 'Grand Blue Dreaming', alternativeTitles: ['Grand Blue'] },
  { title: 'Hinamatsuri', alternativeTitles: [] },
  { title: 'Prison School', alternativeTitles: [] },
  { title: 'Dungeon Meshi', alternativeTitles: ['Delicious in Dungeon'] },
  { title: 'Witch Hat Atelier', alternativeTitles: ['Tongari Boushi no Atelier'] },
  { title: 'The Witch and the Beast', alternativeTitles: ['Majo to Yajuu'] },
];
