/**
 * Training Titles - Shojo & Josei Manga
 */

import type { MangaTitle } from './types';

export const SHOJO_JOSEI_TITLES: MangaTitle[] = [
  // Romance & Drama
  { title: 'Fruits Basket', alternativeTitles: ['Furuba'] },
  { title: 'Ouran High School Host Club', alternativeTitles: [] },
  { title: 'Nana', alternativeTitles: [] },
  { title: 'Banana Fish', alternativeTitles: [] },
  { title: 'Skip Beat!', alternativeTitles: [] },
  { title: 'Kamisama Kiss', alternativeTitles: ['Kamisama Hajimemashita'] },
  { title: 'Maid-sama!', alternativeTitles: ['Kaichou wa Maid-sama!'] },
  { title: 'Kaguya-sama: Love is War', alternativeTitles: ['Kaguya-sama wa Kokurasetai'] },
  { title: 'Horimiya', alternativeTitles: [] },
  { title: 'Wotakoi', alternativeTitles: ['Wotaku ni Koi wa Muzukashii'] },
  { title: 'My Dress-Up Darling', alternativeTitles: ['Sono Bisque Doll wa Koi wo Suru'] },
  { title: 'Kimi ni Todoke', alternativeTitles: ['From Me to You'] },
  { title: 'Ao Haru Ride', alternativeTitles: ['Blue Spring Ride'] },
  { title: 'Strobe Edge', alternativeTitles: [] },
  { title: 'Love Me, Love Me Not', alternativeTitles: ['Omoi, Omoware, Furi, Furare'] },
  { title: 'Lovely Complex', alternativeTitles: ['Love Com'] },
  { title: 'Special A', alternativeTitles: [] },
  { title: 'Vampire Knight', alternativeTitles: [] },
  { title: 'Black Bird', alternativeTitles: [] },
  { title: 'Dengeki Daisy', alternativeTitles: [] },
  { title: 'Inu x Boku SS', alternativeTitles: [] },
  { title: 'My Little Monster', alternativeTitles: ['Tonari no Kaibutsu-kun'] },
  { title: 'Say I Love You', alternativeTitles: ['Sukitte Ii na yo'] },
  { title: 'Orange', alternativeTitles: [] },
  { title: 'We Were There', alternativeTitles: ['Bokura ga Ita'] },
  { title: 'Sand Chronicles', alternativeTitles: ['Sunadokei'] },
  { title: 'His and Her Circumstances', alternativeTitles: ['Kare Kano'] },
  { title: 'Peach Girl', alternativeTitles: [] },
  { title: 'Mars', alternativeTitles: [] },
  { title: 'Marmalade Boy', alternativeTitles: [] },
  { title: 'Itazura na Kiss', alternativeTitles: [] },
  { title: 'Boys Over Flowers', alternativeTitles: ['Hana Yori Dango'] },
  { title: 'High School Debut', alternativeTitles: ['Koukou Debut'] },
  { title: 'My Love Story!!', alternativeTitles: ['Ore Monogatari!!'] },
  { title: 'Honey So Sweet', alternativeTitles: ['Honey'] },
  { title: 'Wolf Girl and Black Prince', alternativeTitles: ['Ookami Shoujo to Kuro Ouji'] },
  { title: 'Shortcake Cake', alternativeTitles: [] },
  { title: 'A Sign of Affection', alternativeTitles: ['Yubisaki to Renren'] },
  { title: 'Takane & Hana', alternativeTitles: [] },
  { title: "Queen's Quality", alternativeTitles: [] },
  { title: 'Daytime Shooting Star', alternativeTitles: ['Hirunaka no Ryuusei'] },
  // Magical Girl & Fantasy
  { title: 'Sailor Moon', alternativeTitles: ['Bishoujo Senshi Sailor Moon'] },
  { title: 'Cardcaptor Sakura', alternativeTitles: ['Card Captor Sakura'] },
  { title: 'Magic Knight Rayearth', alternativeTitles: [] },
  { title: 'Tokyo Mew Mew', alternativeTitles: ['Mew Mew Power'] },
  { title: 'Shugo Chara!', alternativeTitles: [] },
  { title: 'Mermaid Melody Pichi Pichi Pitch', alternativeTitles: [] },
  { title: 'Full Moon wo Sagashite', alternativeTitles: ['Searching for the Full Moon'] },
  { title: 'Kamikaze Kaitou Jeanne', alternativeTitles: ['Phantom Thief Jeanne'] },
  { title: "The Gentlemen's Alliance Cross", alternativeTitles: ['Shinshi Doumei Cross'] },
  { title: 'Sugar Sugar Rune', alternativeTitles: [] },
  { title: 'Saint Tail', alternativeTitles: [] },
  { title: 'Wedding Peach', alternativeTitles: [] },
  { title: 'Pretear', alternativeTitles: [] },
  { title: 'Princess Tutu', alternativeTitles: [] },
  { title: 'Kitchen Princess', alternativeTitles: ['Kitchen no Ohimesama'] },
  { title: 'Gakuen Alice', alternativeTitles: [] },
  // Historical & Fantasy
  { title: 'Fushigi Yuugi', alternativeTitles: ['Curious Play', 'Mysterious Play'] },
  { title: 'Akatsuki no Yona', alternativeTitles: ['Yona of the Dawn'] },
  { title: 'Snow White with the Red Hair', alternativeTitles: ['Akagami no Shirayuki-hime'] },
  { title: 'The Story of Saiunkoku', alternativeTitles: ['Saiunkoku Monogatari'] },
  { title: 'Red River', alternativeTitles: ['Anatolia Story'] },
  { title: 'Basara', alternativeTitles: [] },
  { title: 'Ooku: The Inner Chambers', alternativeTitles: [] },
  { title: 'Ceres, Celestial Legend', alternativeTitles: ['Ayashi no Ceres'] },
  { title: 'Angel Sanctuary', alternativeTitles: ['Tenshi Kinryouku'] },
  { title: 'Please Save My Earth', alternativeTitles: ['Boku no Chikyuu wo Mamotte'] },
  // Josei
  { title: 'Paradise Kiss', alternativeTitles: [] },
  { title: 'Chihayafuru', alternativeTitles: [] },
  { title: 'Princess Jellyfish', alternativeTitles: ['Kuragehime'] },
  { title: 'Nodame Cantabile', alternativeTitles: [] },
  { title: 'Gokusen', alternativeTitles: [] },
  { title: 'Tramps Like Us', alternativeTitles: ['Kimi wa Pet'] },
  { title: 'Midnight Secretary', alternativeTitles: [] },
  { title: 'Usagi Drop', alternativeTitles: ['Bunny Drop'] },
  { title: 'Ristorante Paradiso', alternativeTitles: [] },
  { title: 'Antique Bakery', alternativeTitles: [] },
  // CLAMP Works
  { title: 'X/1999', alternativeTitles: ['X'] },
  { title: 'Tokyo Babylon', alternativeTitles: [] },
  { title: 'RG Veda', alternativeTitles: [] },
  { title: 'Tsubasa: Reservoir Chronicle', alternativeTitles: [] },
  { title: 'xxxHolic', alternativeTitles: [] },
  { title: 'Chobits', alternativeTitles: [] },
  { title: 'Clover', alternativeTitles: [] },
  { title: 'Angelic Layer', alternativeTitles: [] },
  { title: 'Kobato.', alternativeTitles: [] },
];
