/**
 * Training Titles - Shonen Manga
 */

import type { MangaTitle } from './types';

export const SHONEN_TITLES: MangaTitle[] = [
  // Weekly Shonen Jump Classics & Current
  { title: 'One Piece', alternativeTitles: [] },
  { title: 'Naruto', alternativeTitles: [] },
  { title: 'Bleach', alternativeTitles: [] },
  { title: 'Dragon Ball', alternativeTitles: ['Dragon Ball Z', 'Dragon Ball Super'] },
  { title: 'Hunter x Hunter', alternativeTitles: ['Hunter × Hunter'] },
  { title: 'My Hero Academia', alternativeTitles: ['Boku no Hero Academia'] },
  { title: 'Demon Slayer', alternativeTitles: ['Kimetsu no Yaiba'] },
  { title: 'Jujutsu Kaisen', alternativeTitles: [] },
  { title: 'Chainsaw Man', alternativeTitles: [] },
  { title: 'Black Clover', alternativeTitles: [] },
  { title: 'Dr. Stone', alternativeTitles: [] },
  { title: 'Death Note', alternativeTitles: [] },
  { title: 'Attack on Titan', alternativeTitles: ['Shingeki no Kyojin'] },
  { title: 'The Promised Neverland', alternativeTitles: ['Yakusoku no Neverland'] },
  { title: 'Haikyu!!', alternativeTitles: ['Haikyuu'] },
  { title: 'Assassination Classroom', alternativeTitles: ['Ansatsu Kyoushitsu'] },
  { title: 'Gintama', alternativeTitles: [] },
  { title: 'Fullmetal Alchemist', alternativeTitles: ['Hagane no Renkinjutsushi'] },
  { title: 'Yu Yu Hakusho', alternativeTitles: ['Ghost Fighter'] },
  { title: 'Rurouni Kenshin', alternativeTitles: ['Samurai X'] },
  { title: 'Slam Dunk', alternativeTitles: [] },
  { title: 'World Trigger', alternativeTitles: [] },
  { title: 'Spy x Family', alternativeTitles: ['Spy × Family'] },
  { title: 'Mashle', alternativeTitles: ['Mashle: Magic and Muscles'] },
  { title: 'Undead Unluck', alternativeTitles: [] },
  { title: 'Sakamoto Days', alternativeTitles: [] },
  { title: 'Kaiju No. 8', alternativeTitles: [] },
  { title: 'Dandadan', alternativeTitles: [] },
  { title: 'Blue Box', alternativeTitles: ['Ao no Hako'] },
  { title: 'Akane-banashi', alternativeTitles: [] },
  { title: 'Kagurabachi', alternativeTitles: [] },
  { title: 'Mission: Yozakura Family', alternativeTitles: [] },
  { title: 'Me & Roboco', alternativeTitles: [] },
  { title: 'Witch Watch', alternativeTitles: [] },
  { title: 'The Elusive Samurai', alternativeTitles: ['Nige Jouzu no Wakagimi'] },
  { title: 'Oshi no Ko', alternativeTitles: [] },
  { title: 'Frieren', alternativeTitles: ['Sousou no Frieren'] },
  { title: 'Blue Lock', alternativeTitles: [] },
  { title: 'Boruto', alternativeTitles: ['Boruto: Naruto Next Generations'] },
  { title: 'One-Punch Man', alternativeTitles: ['ONE PUNCH MAN'] },
  { title: 'Mob Psycho 100', alternativeTitles: [] },
  { title: 'Fire Force', alternativeTitles: ['Enen no Shouboutai'] },
  { title: 'Soul Eater', alternativeTitles: [] },
  { title: 'Fairy Tail', alternativeTitles: [] },
  { title: 'Rave Master', alternativeTitles: ['Groove Adventure Rave'] },
  { title: 'Edens Zero', alternativeTitles: [] },
  { title: 'The Seven Deadly Sins', alternativeTitles: ['Nanatsu no Taizai'] },
  { title: 'Blue Exorcist', alternativeTitles: ['Ao no Exorcist'] },
  { title: 'Magi', alternativeTitles: ['Magi: The Labyrinth of Magic'] },
  { title: 'D.Gray-man', alternativeTitles: [] },
  { title: 'Claymore', alternativeTitles: [] },
  { title: 'Trigun', alternativeTitles: [] },
  { title: 'Katekyo Hitman Reborn!', alternativeTitles: ['Reborn!'] },
  { title: 'Shaman King', alternativeTitles: [] },
  { title: 'Bakuman', alternativeTitles: [] },
  { title: 'Hikaru no Go', alternativeTitles: [] },
  { title: 'Food Wars!', alternativeTitles: ['Shokugeki no Soma'] },
  { title: 'Toriko', alternativeTitles: [] },
  { title: 'Beelzebub', alternativeTitles: [] },
  { title: 'Psyren', alternativeTitles: [] },
  { title: 'Medaka Box', alternativeTitles: [] },
  { title: 'Sket Dance', alternativeTitles: [] },
  { title: 'Nisekoi', alternativeTitles: [] },
  { title: 'To Love-Ru', alternativeTitles: [] },
  { title: 'We Never Learn', alternativeTitles: ['Bokutachi wa Benkyou ga Dekinai'] },
  { title: 'Act-Age', alternativeTitles: [] },
  { title: 'Saiki K', alternativeTitles: ['The Disastrous Life of Saiki K.'] },
  { title: 'Great Teacher Onizuka', alternativeTitles: ['GTO'] },
  // Weekly Shonen Magazine
  { title: 'Tokyo Revengers', alternativeTitles: [] },
  { title: 'The Quintessential Quintuplets', alternativeTitles: ['Go-Toubun no Hanayome'] },
  { title: 'Rent-A-Girlfriend', alternativeTitles: ['Kanojo, Okarishimasu'] },
  { title: 'A Couple of Cuckoos', alternativeTitles: ['Kakkou no Iinazuke'] },
  { title: 'Hajime no Ippo', alternativeTitles: ['Fighting Spirit'] },
  { title: 'Days', alternativeTitles: [] },
  { title: 'Diamond no Ace', alternativeTitles: ['Ace of Diamond'] },
  { title: 'Baby Steps', alternativeTitles: [] },
  { title: 'Ahiru no Sora', alternativeTitles: [] },
  { title: 'Domestic Girlfriend', alternativeTitles: ['Domestic na Kanojo'] },
  { title: 'Fuuka', alternativeTitles: [] },
  { title: 'Suzuka', alternativeTitles: [] },
  { title: 'GetBackers', alternativeTitles: [] },
  { title: 'Samurai Deeper Kyo', alternativeTitles: [] },
  { title: 'Negima!', alternativeTitles: ['Mahou Sensei Negima!'] },
  { title: 'UQ Holder!', alternativeTitles: [] },
  { title: 'Love Hina', alternativeTitles: [] },
  { title: 'Bloody Monday', alternativeTitles: [] },
  // Weekly Shonen Sunday
  { title: 'Detective Conan', alternativeTitles: ['Case Closed', 'Meitantei Conan'] },
  { title: 'InuYasha', alternativeTitles: [] },
  { title: 'Ranma 1/2', alternativeTitles: [] },
  { title: 'Urusei Yatsura', alternativeTitles: ['Lum'] },
  { title: 'Maison Ikkoku', alternativeTitles: [] },
  { title: 'Zatch Bell!', alternativeTitles: ['Konjiki no Gash!!'] },
  { title: "Komi Can't Communicate", alternativeTitles: ['Komi-san wa, Comyushou desu.'] },
  { title: 'Major', alternativeTitles: [] },
  { title: 'Cross Game', alternativeTitles: [] },
  { title: 'Touch', alternativeTitles: [] },
  { title: 'H2', alternativeTitles: [] },
  { title: 'Mix', alternativeTitles: [] },
  { title: 'Kekkaishi', alternativeTitles: [] },
  { title: 'Hayate the Combat Butler', alternativeTitles: ['Hayate no Gotoku!'] },
  { title: 'Flame of Recca', alternativeTitles: ['Rekka no Honoo'] },
  { title: 'MAR', alternativeTitles: ['Marchen Awakens Romance'] },
  { title: 'Law of Ueki', alternativeTitles: ['Ueki no Housoku'] },
  { title: 'Kenichi: The Mightiest Disciple', alternativeTitles: ['Shijou Saikyou no Deshi Kenichi'] },
  { title: 'Yowamushi Pedal', alternativeTitles: [] },
  { title: 'Tonikawa', alternativeTitles: ['Tonikaku Kawaii'] },
  // Other Shonen Magazines
  { title: 'Baki', alternativeTitles: ['Baki the Grappler'] },
  { title: 'Kengan Ashura', alternativeTitles: [] },
  { title: 'Kengan Omega', alternativeTitles: [] },
  { title: 'Rozen Maiden', alternativeTitles: [] },
  { title: 'Pandora Hearts', alternativeTitles: [] },
  { title: 'Vanitas no Carte', alternativeTitles: ['The Case Study of Vanitas'] },
  { title: 'Bungo Stray Dogs', alternativeTitles: [] },
  { title: 'Black Butler', alternativeTitles: ['Kuroshitsuji'] },
  { title: 'Durarara!!', alternativeTitles: [] },
  { title: 'Baccano!', alternativeTitles: [] },
  { title: 'Deadman Wonderland', alternativeTitles: [] },
  { title: 'Future Diary', alternativeTitles: ['Mirai Nikki'] },
  { title: 'Akame ga Kill!', alternativeTitles: [] },
  { title: 'Summertime Rendering', alternativeTitles: ['Summer Time Render'] },
  { title: 'Shadows House', alternativeTitles: [] },
  { title: "JoJo's Bizarre Adventure", alternativeTitles: ['JoJo no Kimyou na Bouken'] },
  { title: 'Bobobo-bo Bo-bobo', alternativeTitles: [] },
  { title: 'Level E', alternativeTitles: [] },
  { title: 'Houshin Engi', alternativeTitles: ['Soul Hunter'] },
  { title: "Hell's Paradise", alternativeTitles: ['Jigokuraku'] },
  { title: 'Gachiakuta', alternativeTitles: [] },
  { title: 'Zom 100', alternativeTitles: ['Zom 100: Bucket List of the Dead'] },
  { title: 'Choujin X', alternativeTitles: [] },
];
