/**
 * Training Titles - Supplementary Collection
 * Additional unique titles to reach 1000+ target
 */

import type { MangaTitle } from './types';

export const SUPPLEMENTARY_TITLES: MangaTitle[] = [
  // Webcomic Origins
  { title: 'One-Punch Man', alternativeTitles: ['Wanpanman'] },
  { title: 'Mob Psycho 100', alternativeTitles: [] },
  { title: 'Way of the Househusband', alternativeTitles: ['Gokushufudou'] },

  // Recent Shonen Jump
  { title: 'Phantom Seer', alternativeTitles: [] },
  { title: 'Magu-chan: God of Destruction', alternativeTitles: [] },
  { title: 'Build King', alternativeTitles: [] },
  { title: 'Candy Flurry', alternativeTitles: [] },
  { title: 'Nine Dragons\' Ball Parade', alternativeTitles: [] },
  { title: 'i tell c', alternativeTitles: [] },
  { title: 'Red Hood', alternativeTitles: [] },
  { title: 'Neru: Way of the Martial Artist', alternativeTitles: [] },
  { title: 'Protect Me, Shugomaru!', alternativeTitles: [] },
  { title: 'Ginka & Gluna', alternativeTitles: [] },
  { title: 'Astro Royale', alternativeTitles: [] },
  { title: 'Kill Blue', alternativeTitles: [] },
  { title: 'Akane-banashi', alternativeTitles: [] },
  { title: 'Elusive Samurai', alternativeTitles: [] },
  { title: 'Ichigoki', alternativeTitles: [] },

  // Magazine Serializations
  { title: 'Medaka Box', alternativeTitles: [] },
  { title: 'Psyren', alternativeTitles: [] },
  { title: 'Mx0', alternativeTitles: [] },
  { title: 'Double Arts', alternativeTitles: [] },
  { title: 'Enigma', alternativeTitles: [] },
  { title: 'Barrage', alternativeTitles: [] },
  { title: 'Cross Manage', alternativeTitles: [] },
  { title: 'E-Robot', alternativeTitles: [] },
  { title: 'Hungry Joker', alternativeTitles: [] },
  { title: 'Iron Knight', alternativeTitles: [] },
  { title: 'Lady Justice', alternativeTitles: [] },
  { title: 'Lock On!', alternativeTitles: [] },
  { title: 'Magico', alternativeTitles: [] },
  { title: 'Sensei no Bulge', alternativeTitles: [] },
  { title: 'ST&RS', alternativeTitles: [] },
  { title: 'Takama-ga-hara', alternativeTitles: [] },

  // Young Magazine
  { title: 'Akumetsu', alternativeTitles: [] },
  { title: 'Coppelion', alternativeTitles: [] },
  { title: 'Desert Punk', alternativeTitles: ['Sunabouzu'] },
  { title: 'Until Death Do Us Part', alternativeTitles: ['Shi ga Futari wo Wakatsu Made'] },
  { title: 'Jormungand', alternativeTitles: [] },
  { title: 'Zetman', alternativeTitles: [] },
  { title: 'Kimi no Iru Machi', alternativeTitles: ['A Town Where You Live'] },
  { title: 'Fuuka', alternativeTitles: [] },
  { title: 'Minamoto-kun Monogatari', alternativeTitles: [] },
  { title: 'My Wife Is From a Thousand Years Ago', alternativeTitles: [] },
  { title: 'Peach Boy Riverside', alternativeTitles: [] },

  // Big Spirits & Sunday
  { title: 'Ushijima the Loan Shark', alternativeTitles: ['Yamikin Ushijima-kun'] },
  { title: 'Ikigami', alternativeTitles: [] },
  { title: 'Kuragehime', alternativeTitles: ['Princess Jellyfish'] },
  { title: 'Hirunaka no Ryuusei', alternativeTitles: ['Daytime Shooting Star'] },
  { title: 'Takane & Hana', alternativeTitles: [] },
  { title: 'QQ Sweeper', alternativeTitles: [] },
  { title: 'Queen\'s Quality', alternativeTitles: [] },
  { title: 'Shinobi Life', alternativeTitles: [] },
  { title: 'Black Bird', alternativeTitles: [] },
  { title: 'Dengeki Daisy', alternativeTitles: [] },
  { title: 'Faster Than a Kiss', alternativeTitles: [] },
  { title: 'Koko ni Iru yo!', alternativeTitles: ['I Am Here!'] },
  { title: 'Last Game', alternativeTitles: [] },
  { title: 'Lovely Complex', alternativeTitles: [] },
  { title: 'Meteor Prince', alternativeTitles: [] },
  { title: 'Oresama Teacher', alternativeTitles: [] },
  { title: 'Special A', alternativeTitles: [] },
  { title: 'Strobe Edge', alternativeTitles: [] },
  { title: 'Library Wars', alternativeTitles: ['Toshokan Sensou'] },

  // Psychological Thrillers
  { title: 'Prophecy', alternativeTitles: ['Yokokuhan'] },
  { title: 'Route End', alternativeTitles: [] },
  { title: 'Shuumatsu no Walküre', alternativeTitles: ['Record of Ragnarok'] },
  { title: 'Sousei no Taiga', alternativeTitles: [] },
  { title: 'Jagaaan', alternativeTitles: [] },
  { title: 'Happiness', alternativeTitles: [] },
  { title: 'Inside Mari', alternativeTitles: ['Boku wa Mari no Naka'] },
  { title: 'Blood on the Tracks', alternativeTitles: ['Chi no Wadachi'] },
  { title: 'The Flowers of Evil', alternativeTitles: ['Aku no Hana'] },
  { title: 'Himizu', alternativeTitles: [] },
  { title: 'Shamo', alternativeTitles: [] },
  { title: 'Freesia', alternativeTitles: [] },
  { title: 'Homunculus', alternativeTitles: [] },
  { title: 'Kyou Kara Ore Wa!!', alternativeTitles: [] },
  { title: 'Sanctuary', alternativeTitles: [] },
  { title: 'Old Boy', alternativeTitles: [] },
  { title: 'Ichi The Killer', alternativeTitles: [] },

  // Light Novel Adaptations
  { title: 'Baccano!', alternativeTitles: [] },
  { title: 'Durarara!!', alternativeTitles: [] },
  { title: 'Kara no Kyoukai', alternativeTitles: ['The Garden of Sinners'] },
  { title: 'Fate/Zero', alternativeTitles: [] },
  { title: 'Fate/Apocrypha', alternativeTitles: [] },
  { title: 'Fate/strange Fake', alternativeTitles: [] },
  { title: 'Lord El-Melloi II Case Files', alternativeTitles: [] },
  { title: 'Tsukihime', alternativeTitles: [] },
  { title: 'The Irregular at Magic High School', alternativeTitles: [] },
  { title: 'A Certain Magical Index', alternativeTitles: ['Toaru Majutsu no Index'] },
  { title: 'A Certain Scientific Railgun', alternativeTitles: ['Toaru Kagaku no Railgun'] },
  { title: 'A Certain Scientific Accelerator', alternativeTitles: [] },
  { title: 'Oreimo', alternativeTitles: [] },
  { title: 'Eromanga Sensei', alternativeTitles: [] },
  { title: 'Toradora!', alternativeTitles: [] },
  { title: 'Shakugan no Shana', alternativeTitles: [] },
  { title: 'Zero no Tsukaima', alternativeTitles: ['The Familiar of Zero'] },
  { title: 'Haruhi Suzumiya', alternativeTitles: ['The Melancholy of Haruhi Suzumiya'] },
  { title: 'Bakemonogatari', alternativeTitles: [] },
  { title: 'Nisemonogatari', alternativeTitles: [] },
  { title: 'Nekomonogatari', alternativeTitles: [] },
  { title: 'Kizumonogatari', alternativeTitles: [] },

  // Video Game Adaptations
  { title: 'Persona 3', alternativeTitles: [] },
  { title: 'Persona 4', alternativeTitles: [] },
  { title: 'Persona 5', alternativeTitles: [] },
  { title: 'Fire Emblem', alternativeTitles: [] },
  { title: 'Tales of Symphonia', alternativeTitles: [] },
  { title: 'Tales of the Abyss', alternativeTitles: [] },
  { title: 'Nier: Automata', alternativeTitles: [] },
  { title: 'Devil May Cry', alternativeTitles: [] },
  { title: 'Resident Evil', alternativeTitles: ['Biohazard'] },
  { title: 'Castlevania', alternativeTitles: [] },
  { title: 'Splatoon', alternativeTitles: [] },
  { title: 'Zelda no Densetsu', alternativeTitles: ['The Legend of Zelda'] },
  { title: 'Kirby', alternativeTitles: [] },
  { title: 'Kid Icarus: Uprising', alternativeTitles: [] },
];
