-- Define the NotificationEventType enum that this table column depends on.
-- The original CREATE TYPE was lost in a history squash; we re-add it here
-- idempotently so fresh installs apply cleanly.
DO $$ BEGIN
    CREATE TYPE "NotificationEventType" AS ENUM (
        'MANGA_ADDED', 'MANGA_UPDATED', 'MANGA_DELETED',
        'CHAPTER_ADDED', 'CHAPTER_DOWNLOADED', 'CHAPTER_FAILED',
        'VOLUME_ADDED', 'VOLUME_DOWNLOADED',
        'METADATA_UPDATED',
        'SYNC_STARTED', 'SYNC_COMPLETED', 'SYNC_FAILED',
        'BACKUP_STARTED', 'BACKUP_COMPLETED', 'BACKUP_FAILED',
        'SYSTEM_ERROR', 'SYSTEM_WARNING', 'SYSTEM_INFO',
        'USER_ACTION',
        'SUWAYOMI_SERVER_CONNECTED', 'SUWAYOMI_SERVER_DISCONNECTED',
        'SUWAYOMI_SERVER_HEALTH_CHECK_FAILED',
        'SUWAYOMI_SOURCE_INSTALLED', 'SUWAYOMI_SOURCE_UNINSTALLED',
        'SUWAYOMI_SEARCH_STARTED', 'SUWAYOMI_SEARCH_COMPLETED', 'SUWAYOMI_SEARCH_FAILED',
        'SUWAYOMI_CHAPTER_DOWNLOAD_STARTED', 'SUWAYOMI_CHAPTER_DOWNLOAD_COMPLETED',
        'SUWAYOMI_CHAPTER_DOWNLOAD_FAILED',
        'SUWAYOMI_MANGA_FETCHED', 'SUWAYOMI_CHAPTERS_FETCHED',
        'NATIVE_DOWNLOAD_SOURCE_INITIALIZED',
        'NATIVE_DOWNLOAD_SOURCE_VALIDATION_STARTED',
        'NATIVE_DOWNLOAD_SOURCE_VALIDATION_COMPLETED',
        'NATIVE_DOWNLOAD_SOURCE_VALIDATION_FAILED',
        'NATIVE_DOWNLOAD_SOURCE_ERROR',
        'NATIVE_DOWNLOAD_QUEUED', 'NATIVE_DOWNLOAD_STARTED',
        'NATIVE_DOWNLOAD_PROGRESS', 'NATIVE_DOWNLOAD_COMPLETED',
        'NATIVE_DOWNLOAD_FAILED', 'NATIVE_DOWNLOAD_MANAGER_INITIALIZED',
        'PROWLARR_CONNECTED', 'PROWLARR_DISCONNECTED',
        'PROWLARR_CONNECTION_TEST_SUCCESSFUL', 'PROWLARR_CONNECTION_TEST_FAILED',
        'PROWLARR_INDEXER_TEST_FAILED',
        'PROWLARR_SEARCH_STARTED', 'PROWLARR_SEARCH_COMPLETED', 'PROWLARR_SEARCH_FAILED',
        'UPDATE_AVAILABLE', 'DOWNLOAD_FAILED', 'TASK_FAILED',
        'SUWAYOMI_EXTENSION_UPDATED', 'SUWAYOMI_EXTENSION_INSTALLED',
        'SUWAYOMI_EXTENSION_UNINSTALLED',
        'SUWAYOMI_BACKUP_CREATED', 'SUWAYOMI_BACKUP_RESTORED', 'SUWAYOMI_BACKUP_FAILED',
        'SUWAYOMI_LIBRARY_UPDATED',
        'SUWAYOMI_UPDATE_CHECK_STARTED', 'SUWAYOMI_UPDATE_CHECK_COMPLETED',
        'SUWAYOMI_UPDATE_CHECK_FAILED',
        'SUWAYOMI_DOWNLOAD_QUEUE_UPDATED', 'SUWAYOMI_SETTING_CHANGED',
        'SUWAYOMI_CATEGORY_CREATED', 'SUWAYOMI_CATEGORY_DELETED',
        'SUWAYOMI_CATEGORY_UPDATED', 'SUWAYOMI_MANGA_MIGRATED',
        'SUWAYOMI_TRACKER_LOGIN_SUCCESS', 'SUWAYOMI_TRACKER_LOGIN_FAILED',
        'SUWAYOMI_TRACKER_UPDATE_SUCCESS', 'SUWAYOMI_TRACKER_UPDATE_FAILED',
        'TASK_STARTED', 'TASK_COMPLETED',
        'DOWNLOAD_STARTED', 'DOWNLOAD_COMPLETED',
        'UPDATE_INSTALLED', 'UPDATE_FAILED',
        'LIBRARY_SCAN_STARTED', 'LIBRARY_SCAN_COMPLETED', 'LIBRARY_SCAN_FAILED',
        'USER_LOGIN', 'USER_LOGOUT', 'USER_REGISTERED',
        'SETTINGS_CHANGED',
        'API_ERROR', 'API_WARNING'
    );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- CreateTable
CREATE TABLE IF NOT EXISTS "NotificationPreference" (
    "id" SERIAL NOT NULL,
    "userId" TEXT NOT NULL,
    "eventType" "NotificationEventType" NOT NULL,
    "channel" TEXT NOT NULL,
    "enabled" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "NotificationPreference_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX IF NOT EXISTS "NotificationPreference_userId_idx" ON "NotificationPreference"("userId");

-- CreateIndex
CREATE UNIQUE INDEX IF NOT EXISTS "NotificationPreference_userId_eventType_channel_key" ON "NotificationPreference"("userId", "eventType", "channel");

-- AddForeignKey
DO $$ BEGIN
    ALTER TABLE "NotificationPreference" ADD CONSTRAINT "NotificationPreference_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

