
/**
 * Type Guards for Safe Property Access
 * Auto-generated by Phase 2.1 migration
 */

export function hasProperty<T, K extends PropertyKey>(
  obj: T, prop: K
): obj is T & Record<K, unknown> {
  return obj !== null && prop in (obj as Record<PropertyKey, unknown>);
}

export function hasArrayProperty<T, K extends PropertyKey>(
  obj: T, prop: K
): obj is T & Record<K, unknown[]> {
  return hasProperty(obj, prop) && Array.isArray((obj as Record<K, unknown>)[prop]);
}

export function safeArrayLength(arr: unknown): number {
  return Array.isArray(arr) ? arr.length : 0;
}

export function safePropertyAccess<T, R>(
  obj: T, accessor: (obj: T) => R, defaultValue: R
): R {
  try {
    const result = accessor(obj);
    return result ?? defaultValue;
  } catch {
    return defaultValue;
  }
}
