#!/bin/bash
# =============================================================================
# DOCKER ENTRYPOINT SCRIPT
# =============================================================================
# This script runs inside the Docker container as the entrypoint
# It handles database setup and application startup
# =============================================================================

set -e  # Exit on any error

# Color output for better readability
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}🐳 Starting Kaizoku in Docker container${NC}"

# =============================================================================
# SECRETS BOOTSTRAP
# =============================================================================
# Auto-generate NEXTAUTH_SECRET / AUTH_SECRET on first boot and persist to
# the config volume. Explicit env vars always win — this only kicks in
# when both are unset or empty.
#
# Path resolution: prefer /config (linuxserver convention, used post-Phase-B)
# but fall back to /app/config which is what the current compose mounts.
# =============================================================================
if [ -d "/config" ] && [ -w "/config" ]; then
  SECRETS_FILE="/config/secrets.env"
elif [ -d "/app/config" ]; then
  mkdir -p /app/config 2>/dev/null || true
  SECRETS_FILE="/app/config/secrets.env"
else
  # Last-resort: write inside the container (won't persist across recreates)
  mkdir -p /app/config 2>/dev/null || true
  SECRETS_FILE="/app/config/secrets.env"
fi

# Pull in already-persisted secrets if env doesn't override them
if [ -f "$SECRETS_FILE" ]; then
  echo -e "${BLUE}🔑 Loading persisted secrets from $SECRETS_FILE${NC}"
  # shellcheck disable=SC1090
  set -a; . "$SECRETS_FILE"; set +a
fi

if [ -z "${NEXTAUTH_SECRET:-}" ] || [ -z "${AUTH_SECRET:-}" ]; then
  echo -e "${YELLOW}🔑 No secrets found — generating and persisting to $SECRETS_FILE${NC}"
  mkdir -p "$(dirname "$SECRETS_FILE")"
  : "${NEXTAUTH_SECRET:=$(openssl rand -base64 32)}"
  : "${AUTH_SECRET:=$(openssl rand -base64 32)}"
  {
    echo "# Auto-generated by docker-entrypoint.sh on $(date -u +%FT%TZ)"
    echo "# Do not commit. Override either value by setting the env var in compose."
    echo "NEXTAUTH_SECRET=$NEXTAUTH_SECRET"
    echo "AUTH_SECRET=$AUTH_SECRET"
  } > "$SECRETS_FILE"
  chmod 600 "$SECRETS_FILE" 2>/dev/null || true
  export NEXTAUTH_SECRET AUTH_SECRET
  echo -e "${GREEN}✅ Secrets generated. Persisted to $SECRETS_FILE (chmod 600).${NC}"
fi

# Check environment
if [[ "$NODE_ENV" == "production" ]]; then
  echo -e "${YELLOW}Production mode detected - using migration-based setup${NC}"
  
  # In production, use the migration-based approach
  echo -e "${BLUE}🔄 Running migrations...${NC}"
  bunx prisma migrate deploy
  
  # Start the unified server (all services + WebSocket)
  echo -e "${GREEN}✅ Database setup complete. Starting application...${NC}"
  exec bun src/server/index.ts
else
  echo -e "${YELLOW}Development mode detected - using schema recreation${NC}"
  
  # In development, use the schema recreation approach
  echo -e "${BLUE}📋 Setting up development database...${NC}"
  
  # Ensure we're using the consolidated schema
  if [[ -f "prisma/schema-consolidated.prisma" ]]; then
    echo -e "${BLUE}🔄 Using consolidated schema...${NC}"
    cp prisma/schema-consolidated.prisma prisma/schema.prisma
  fi
  
  # Generate Prisma client
  echo -e "${BLUE}⚙️  Generating Prisma client...${NC}"
  bunx prisma generate
  
  # Reset database (drops all data and recreates from schema)
  echo -e "${YELLOW}⚠️  Recreating database from schema...${NC}"
  bunx prisma db push --force-reset
  
  # Run the development seed script
  echo -e "${BLUE}🌱 Running development seed script...${NC}"
  node scripts/database/seed-dev.js
  
  # Start the application in development mode
  echo -e "${GREEN}✅ Development database setup complete. Starting application...${NC}"
  bun run dev
fi