#!/bin/bash
# =============================================================================
# DOCKER ENTRYPOINT SCRIPT
# =============================================================================
# Runs as root. Orchestrates:
#   1. Secrets bootstrap   — auto-generate NEXTAUTH_SECRET / AUTH_SECRET
#   2. Postgres bootstrap  — initdb + start bundled PG if DATABASE_URL points
#                            at localhost (skipped if external DB configured)
#   3. Migrations          — `bunx prisma migrate deploy`
#   4. App launch          — gosu app exec bun src/server/index.ts
#
# Single-container mode (default): DATABASE_URL unset or localhost → bundled
# postgres starts internally.
# Multi-container mode: DATABASE_URL points to external host → bundled
# postgres is skipped; we just wait for the external DB to be reachable.
# =============================================================================

set -e

# Color output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo -e "${BLUE}🐳 Starting Kaizoku in Docker container${NC}"

# =============================================================================
# 0. CONFIG DIR LAYOUT
# =============================================================================
# Single user-mounted directory holds everything persistent. Subdirs:
#   /config/secrets.env  — auto-generated session secrets
#   /config/postgres     — bundled Postgres data (PGDATA)
#   /config/data         — app state: libraries metadata, downloads, suwayomi
#   /config/logs         — app logs
# Entrypoint creates + chowns these on every boot so a fresh user-mounted
# host dir Just Works (Docker volumes inherit host ownership which is
# usually wrong for the postgres user).
mkdir -p /config /config/data /config/logs /config/postgres
chown app:app /config /config/data /config/logs
chown postgres:postgres /config/postgres
chmod 700 /config/postgres

SECRETS_FILE="/config/secrets.env"

if [ -f "$SECRETS_FILE" ]; then
  echo -e "${BLUE}🔑 Loading persisted secrets from $SECRETS_FILE${NC}"
  # shellcheck disable=SC1090
  set -a; . "$SECRETS_FILE"; set +a
fi

if [ -z "${NEXTAUTH_SECRET:-}" ] || [ -z "${AUTH_SECRET:-}" ]; then
  echo -e "${YELLOW}🔑 No secrets found — generating and persisting${NC}"
  mkdir -p "$(dirname "$SECRETS_FILE")"
  : "${NEXTAUTH_SECRET:=$(openssl rand -base64 32)}"
  : "${AUTH_SECRET:=$(openssl rand -base64 32)}"
  {
    echo "# Auto-generated by docker-entrypoint.sh on $(date -u +%FT%TZ)"
    echo "# Do not commit. Override either value by setting the env var in compose."
    echo "NEXTAUTH_SECRET=$NEXTAUTH_SECRET"
    echo "AUTH_SECRET=$AUTH_SECRET"
  } > "$SECRETS_FILE"
  chmod 600 "$SECRETS_FILE" 2>/dev/null || true
  export NEXTAUTH_SECRET AUTH_SECRET
  echo -e "${GREEN}✅ Secrets generated. Persisted to $SECRETS_FILE (chmod 600).${NC}"
fi

# =============================================================================
# 2. POSTGRES BOOTSTRAP (bundled DB)
# =============================================================================
# Defaults:
#   DATABASE_URL=postgresql://kaizoku:kaizoku@localhost:5432/kaizoku
#   PGDATA=/data/postgres
#
# If DATABASE_URL is already set to an EXTERNAL host (anything that's not
# localhost / 127.0.0.1), we skip starting the bundled postgres entirely.
: "${PGDATA:=/data/postgres}"
: "${POSTGRES_USER:=kaizoku}"
: "${POSTGRES_PASSWORD:=kaizoku}"
: "${POSTGRES_DB:=kaizoku}"
: "${DATABASE_URL:=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@localhost:5432/${POSTGRES_DB}}"
export PGDATA DATABASE_URL

POSTGRES_PID=""
db_host_from_url() {
  # Extract host between "@" and ":"/"/" in postgresql://user:pass@host:port/db
  echo "$DATABASE_URL" | sed -nE 's|^postgres(ql)?://[^@]+@([^:/]+).*|\2|p'
}
DB_HOST="$(db_host_from_url)"

start_bundled_postgres=false
case "$DB_HOST" in
  localhost|127.0.0.1|"")
    start_bundled_postgres=true
    ;;
  *)
    echo -e "${BLUE}🐘 External database detected ($DB_HOST) — skipping bundled postgres${NC}"
    ;;
esac

if [ "$start_bundled_postgres" = "true" ]; then
  # Ensure data dir exists with the right owner
  mkdir -p "$PGDATA"
  chown -R postgres:postgres "$PGDATA"
  chmod 700 "$PGDATA"

  # Ensure unix socket dir exists on every boot (lost on container recreate)
  mkdir -p /var/run/postgresql && chown postgres:postgres /var/run/postgresql

  if [ ! -s "$PGDATA/PG_VERSION" ]; then
    echo -e "${YELLOW}🐘 First-run: initializing PostgreSQL cluster at $PGDATA${NC}"
    PW_FILE="$(mktemp)"
    echo "$POSTGRES_PASSWORD" > "$PW_FILE"
    chown postgres:postgres "$PW_FILE"
    gosu postgres /usr/lib/postgresql/15/bin/initdb \
      -D "$PGDATA" \
      --auth-local=trust \
      --auth-host=md5 \
      --username="$POSTGRES_USER" \
      --pwfile="$PW_FILE" \
      --encoding=UTF8 \
      --locale=C.UTF-8
    rm -f "$PW_FILE"

    # Listen only on localhost (no external surface) + use Unix socket dir
    {
      echo "listen_addresses = 'localhost'"
      echo "unix_socket_directories = '/var/run/postgresql'"
    } >> "$PGDATA/postgresql.conf"
    echo -e "${GREEN}✅ PostgreSQL cluster initialized${NC}"
  fi

  # Start postgres in the background — runs for the lifetime of the container
  echo -e "${BLUE}🐘 Starting bundled PostgreSQL${NC}"
  gosu postgres /usr/lib/postgresql/15/bin/postgres -D "$PGDATA" &
  POSTGRES_PID=$!

  # Wait for postgres to accept connections before any psql work.
  # initdb created the cluster with --username=$POSTGRES_USER, so there is
  # NO 'postgres' role — every psql / pg_isready call must explicitly
  # pass -U "$POSTGRES_USER".
  for i in $(seq 1 30); do
    if gosu postgres pg_isready -h /var/run/postgresql -U "$POSTGRES_USER" -q; then
      break
    fi
    if [ "$i" -eq 30 ]; then
      echo -e "${RED}❌ PostgreSQL failed to become ready within 30s${NC}"
      exit 1
    fi
    sleep 1
  done

  # Idempotent database bootstrap (runs every boot — safe to re-run).
  # Connects to the built-in 'postgres' maintenance database as the
  # superuser created by initdb ($POSTGRES_USER, not the system 'postgres'
  # role which doesn't exist in this cluster).
  DB_EXISTS=$(gosu postgres /usr/lib/postgresql/15/bin/psql -h /var/run/postgresql -U "$POSTGRES_USER" -d postgres -tAc \
    "SELECT 1 FROM pg_database WHERE datname='${POSTGRES_DB}'" 2>/dev/null || echo "")
  if [ "$DB_EXISTS" != "1" ]; then
    echo -e "${BLUE}🐘 Creating database '$POSTGRES_DB'${NC}"
    gosu postgres /usr/lib/postgresql/15/bin/psql -h /var/run/postgresql -U "$POSTGRES_USER" -d postgres -v ON_ERROR_STOP=1 \
      -c "CREATE DATABASE \"${POSTGRES_DB}\" OWNER \"${POSTGRES_USER}\";"
  fi

  # Trap SIGTERM/SIGINT to bring postgres down cleanly when the container stops
  cleanup() {
    if [ -n "$POSTGRES_PID" ] && kill -0 "$POSTGRES_PID" 2>/dev/null; then
      echo -e "${YELLOW}📡 Stopping PostgreSQL (pid $POSTGRES_PID)${NC}"
      kill -TERM "$POSTGRES_PID" 2>/dev/null || true
      wait "$POSTGRES_PID" 2>/dev/null || true
    fi
  }
  trap cleanup SIGTERM SIGINT EXIT
fi

# Wait for the database (bundled or external) to be reachable
echo -e "${BLUE}⏳ Waiting for database${NC}"
for i in $(seq 1 60); do
  if pg_isready -d "$DATABASE_URL" >/dev/null 2>&1; then
    echo -e "${GREEN}✅ Database is ready${NC}"
    break
  fi
  if [ "$i" -eq 60 ]; then
    echo -e "${RED}❌ Database failed to become ready within 60s${NC}"
    exit 1
  fi
  sleep 1
done

# =============================================================================
# 3. MIGRATIONS + APP LAUNCH
# =============================================================================
if [[ "$NODE_ENV" == "production" ]]; then
  echo -e "${BLUE}🔄 Running Prisma migrations${NC}"

  # Auto-recover from P3009 — a previous container exit (e.g. SIGILL) can
  # leave a migration marked "started but not finished" in _prisma_migrations,
  # after which `prisma migrate deploy` refuses to proceed. Detect the stuck
  # row, mark it rolled-back, retry once.
  if ! gosu app env DATABASE_URL="$DATABASE_URL" bunx prisma migrate deploy; then
    STUCK_MIG=""
    if [ "$start_bundled_postgres" = "true" ]; then
      STUCK_MIG=$(gosu postgres /usr/lib/postgresql/15/bin/psql \
        -h /var/run/postgresql -U "$POSTGRES_USER" -d "$POSTGRES_DB" -tAc \
        "SELECT migration_name FROM _prisma_migrations WHERE finished_at IS NULL AND rolled_back_at IS NULL ORDER BY started_at DESC LIMIT 1;" \
        2>/dev/null | tr -d '[:space:]' || true)
    fi
    if [ -n "$STUCK_MIG" ]; then
      echo -e "${YELLOW}⚠️  Found stuck migration '$STUCK_MIG' — marking rolled-back and retrying${NC}"
      gosu app env DATABASE_URL="$DATABASE_URL" bunx prisma migrate resolve --rolled-back "$STUCK_MIG"
      gosu app env DATABASE_URL="$DATABASE_URL" bunx prisma migrate deploy
    else
      echo -e "${RED}❌ Migration failed and no stuck row found — manual intervention needed${NC}"
      exit 1
    fi
  fi

  echo -e "${GREEN}✅ Database setup complete. Starting application${NC}"
  # exec into the app under the 'app' user. If bundled postgres is running,
  # it stays as a child of this process (PID 1 is the entrypoint shell).
  if [ "$start_bundled_postgres" = "true" ]; then
    # Keep postgres as a sibling — run app in foreground, NOT exec
    gosu app env DATABASE_URL="$DATABASE_URL" \
      NEXTAUTH_SECRET="$NEXTAUTH_SECRET" \
      AUTH_SECRET="$AUTH_SECRET" \
      "$@"
    APP_EXIT=$?
    cleanup
    exit $APP_EXIT
  else
    exec gosu app env DATABASE_URL="$DATABASE_URL" \
      NEXTAUTH_SECRET="$NEXTAUTH_SECRET" \
      AUTH_SECRET="$AUTH_SECRET" \
      "$@"
  fi
else
  echo -e "${YELLOW}Development mode detected${NC}"
  gosu app bunx prisma generate
  gosu app bunx prisma db push --force-reset
  [ -f scripts/database/seed-dev.js ] && gosu app bun scripts/database/seed-dev.js || true
  exec gosu app "$@"
fi
